-- LLM incident-explanation / shift-report / NL-query copilot — audited,
-- persisted follow-up to the RBAC and breakdown-report migrations
-- (20260805210000__ops_rbac.sql, 20260806120000__ops_breakdown_reports.sql).
--
-- Two tables:
--   ops_copilot_interactions — append-only log of every prompt/response the
--     copilot module sends to/receives from the LLM whenever incident or
--     audit data is in scope (ticket AC: "LLM prompts/responses touching
--     incident data logged for audit"). Same append-only-by-trigger shape
--     as ops_audit_log, for the same reason: an audit record that can be
--     quietly edited or deleted after the fact is not an audit record.
--   ops_shift_report_drafts — AI-drafted shift-report content. Always
--     created with status='draft' and ai_drafted=true; the status only ever
--     advances to 'saved' or 'sent' through an explicit follow-up write
--     (POST .../finalize) attributed to a human ops_users row — nothing in
--     this schema or the app code that writes to it can set status to
--     anything but 'draft' at INSERT time (see the check constraint below
--     and src/lib/copilot/repo.ts createShiftReportDraft, which never
--     accepts a caller-supplied status). That is what makes "never
--     auto-publish" a database-level guarantee, not just an application
--     convention.
--
-- Both tables are keyed to ops_users (this app's own RBAC identity), the
-- same attribution pattern as ops_dispatcher_actions / ops_breakdown_reports.
-- Neither table is written to by, or grants any access to,
-- ops_dispatcher_actions / the control-room commands endpoint — the copilot
-- module this migration supports is a strictly read-grounded, additive
-- surface (docs/olympuss/COPILOT.md), never a path back into command
-- creation or dispatcher-action consumption.
--
-- Idempotent: every statement is safe to re-run. Do not edit this file once
-- applied anywhere; add a new migration for any follow-up change.

begin;

-- ============================================================================
-- ops_copilot_interactions — append-only, every LLM call attributable to a user
-- ============================================================================

create table if not exists ops_copilot_interactions (
  id                  uuid primary key default gen_random_uuid(),
  kind                text not null check (kind in ('incident_explanation', 'shift_report_draft', 'nl_query')),
  actor_user_id       uuid not null references ops_users (id) on delete restrict,
  actor_role          text not null,
  incident_id         text,
  route_direction_id  text,
  question            text,
  prompt              text not null,
  response            text,
  source_record_ids   jsonb not null default '[]'::jsonb,
  model               text not null,
  status              text not null check (status in ('ok', 'error')),
  error_message       text,
  created_at          timestamptz not null default now()
);

comment on table ops_copilot_interactions is
  'Append-only audit log of every copilot LLM call that touched incident/audit data: the exact prompt sent, the response received (or the error, if the call failed), and the source_record_ids the answer was grounded in. Written by src/lib/copilot/repo.ts logCopilotInteraction, once per call, whether it succeeds or fails — a failed call is still logged (status=''error'', response=null) so a silently-degraded copilot is still visible in the audit trail.';

create index if not exists ops_copilot_interactions_actor_idx on ops_copilot_interactions (actor_user_id, created_at desc);
create index if not exists ops_copilot_interactions_incident_idx on ops_copilot_interactions (incident_id) where incident_id is not null;
create index if not exists ops_copilot_interactions_kind_idx on ops_copilot_interactions (kind, created_at desc);

create or replace function ops_copilot_interactions_prevent_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'ops_copilot_interactions is append-only; % is not permitted', tg_op;
end;
$$;

drop trigger if exists prevent_update on ops_copilot_interactions;
create trigger prevent_update before update on ops_copilot_interactions
  for each row execute function ops_copilot_interactions_prevent_mutation();

drop trigger if exists prevent_delete on ops_copilot_interactions;
create trigger prevent_delete before delete on ops_copilot_interactions
  for each row execute function ops_copilot_interactions_prevent_mutation();

-- ============================================================================
-- ops_shift_report_drafts — AI-drafted, human-finalized shift reports
-- ============================================================================

create table if not exists ops_shift_report_drafts (
  id                  uuid primary key default gen_random_uuid(),
  shift_label         text not null,
  period_start        timestamptz not null,
  period_end          timestamptz not null,
  route_direction_id  text,
  content             text not null,
  ai_drafted          boolean not null default true,
  source_record_ids   jsonb not null default '[]'::jsonb,
  status              text not null default 'draft' check (status in ('draft', 'saved', 'sent')),
  created_by          uuid not null references ops_users (id) on delete restrict,
  created_at          timestamptz not null default now(),
  saved_by            uuid references ops_users (id) on delete set null,
  saved_at            timestamptz,
  sent_by             uuid references ops_users (id) on delete set null,
  sent_at             timestamptz,
  check (period_end >= period_start),
  check (ai_drafted = true),
  check (status <> 'saved' or saved_by is not null),
  check (status <> 'sent' or sent_by is not null)
);

comment on table ops_shift_report_drafts is
  'One row per AI-drafted shift-report handoff. Always INSERTed with status=''draft'' (application code never accepts a caller-supplied status on create — see src/lib/copilot/repo.ts createShiftReportDraft); the CHECK constraints above additionally make it impossible for a ''saved''/''sent'' row to exist without a human saved_by/sent_by attribution. There is no automated job anywhere that transitions a draft''s status — the only writer of saved_at/sent_at is POST /api/ops/control-room/copilot/shift-reports/[id]/finalize, which requires an authenticated ops session per call.';

create index if not exists ops_shift_report_drafts_status_idx on ops_shift_report_drafts (status, created_at desc);
create index if not exists ops_shift_report_drafts_created_by_idx on ops_shift_report_drafts (created_by, created_at desc);

commit;
