-- Adds ops_users.vehicle_id, an admin-set driver/pilot_driver-to-vehicle
-- assignment, replacing (where set) the self-reported-vehicle-registration-
-- remembered-in-localStorage convention the driver-facing UI has used until
-- now (DriverDashboard's schedule lookup, BreakdownReportPanel's vehicle
-- field, and the pilot-driver command console's own vehicle field).
--
-- vehicle_id is a free-text vehicle identifier/registration, not a foreign
-- key: this app's own datastore (../README.md) has no vehicles table.
-- Fleet/vehicle data lives upstream and is read via GET /api/ops/fleet/
-- schedule. This mirrors ops_dispatcher_actions.vehicle_id's existing
-- text-column convention from the parent RBAC migration
-- (20260805210000__ops_rbac.sql).
--
-- Nullable: most rows will have no assignment until an admin sets one via
-- POST /api/ops/admin/users/:id/vehicle. Every read site must keep falling
-- back to the pre-existing self-report convention when this is null, so a
-- not-yet-assigned driver is never blocked from using their dashboard.
--
-- Idempotent: safe to re-run. Do not edit this file once applied anywhere;
-- add a new migration for any follow-up change.

begin;

alter table ops_users add column if not exists vehicle_id text;

comment on column ops_users.vehicle_id is
  'Admin-assigned vehicle registration for driver/pilot_driver accounts, set via POST /api/ops/admin/users/:id/vehicle. Null until an admin assigns one, in which case callers fall back to the pre-existing client-self-reported vehicle. Exposed to the owning user via GET /api/ops/auth/session (vehicleId).';

create index if not exists ops_users_vehicle_id_idx on ops_users (vehicle_id) where vehicle_id is not null;

commit;
