-- Real driver-to-vehicle assignment for the ops RBAC schema — closes the A01
-- gap described in this migration's ticket: POST
-- /api/ops/pilot-driver/commands/:id/ack (and GET
-- /api/ops/pilot-driver/commands) previously trusted a client-supplied
-- `vehicleId` with no check that the calling driver was actually assigned
-- that vehicle, so any `pilot_driver` account could claim an arbitrary
-- vehicleId and observe/ack that vehicle's commands.
--
-- Follow-up to the parent RBAC migration (20260805210000__ops_rbac.sql) and
-- the pilot_driver role migration (20260806160000__ops_pilot_driver_role.sql).
--
-- Nullable and admin-set only: a driver never sets their own vehicle_id (no
-- route lets a non-admin caller write this column — see
-- src/app/api/ops/admin/users/[id]/vehicle/route.ts and the optional
-- `vehicleId` on POST /api/ops/admin/invites). Nullable because an account
-- can exist before it is assigned a vehicle (e.g. immediately after invite
-- acceptance, before an admin has assigned one) — callers must treat
-- null as "no vehicle assigned yet", not fall back to trusting client input.
--
-- No FK to a vehicles table: this app's own schema
-- (db/migrations/*.sql) has no vehicles table of its own — fleet/vehicle
-- identity lives in the separate control-service datastore
-- (docs/CONTROL_SERVICE_INTEGRATION.md §1, §3), which this app never shares
-- a database with. `vehicle_id` here is the same free-text vehicle
-- registration/id convention already used by ops_dispatcher_actions.vehicle_id
-- and ops_breakdown_reports.vehicle_reg.
--
-- Idempotent: safe to re-run. Do not edit this file once applied anywhere;
-- add a new migration for any follow-up change.

begin;

alter table ops_users add column if not exists vehicle_id text;

comment on column ops_users.vehicle_id is
  'The vehicle this driver/pilot_driver is assigned to, set only by an admin (POST /api/ops/admin/users/:id/vehicle, or at invite time via ops_invites.vehicle_id). Null means "not yet assigned" — never fall back to a client-supplied vehicleId when this is null. Meaningless for non-driver roles but left ungated at the schema level, same as ops_dispatcher_actions.vehicle_id being nullable for action_types that do not target a vehicle.';

-- Lets an admin assign the vehicle at invite time (copied onto ops_users by
-- acceptInvite in src/lib/auth/rbac/repo.ts) instead of requiring a second
-- admin action right after the invite is accepted.
alter table ops_invites add column if not exists vehicle_id text;

comment on column ops_invites.vehicle_id is
  'Optional vehicle assignment to apply to the ops_users row created when this invite is accepted (see acceptInvite in src/lib/auth/rbac/repo.ts). Null is valid — the admin can assign a vehicle later via POST /api/ops/admin/users/:id/vehicle instead.';

commit;
