-- Inbound control-service -> web webhook receipts, plus this app's read-only
-- mirror of control-service command lifecycle state.
--
-- Backs POST /api/control-service/webhook (src/app/api/control-service/webhook/
-- route.ts), the handler for the signed deliveries described in
-- docs/CONTROL_SERVICE_INTEGRATION.md §1 "Control service -> web". Before this
-- migration the web app had no receiver at all: control-service POSTed to
-- WEB_APP_WEBHOOK_URL, got a 404, and — because its retry policy only retries
-- 408/429/5xx (control-service/src/webhooks/dispatch.ts) — dropped every event
-- after a single attempt. The control room could only learn that a driver
-- responded UNABLE/UNSAFE by polling.
--
-- This is THIS APP'S OWN datastore (OPS_DATABASE_URL, src/lib/db/pool.ts), not
-- the control service's Postgres/PostGIS store. The two remain isolated
-- (docs/CONTROL_SERVICE_INTEGRATION.md §3, control-service/README.md): nothing
-- here is a foreign key into control-service, and this app never writes to
-- control-service's `commands` table. `ops_command_mirror` is a *projection*
-- of state control-service owns, kept current by the webhook — control-service
-- stays the source of truth, and any disagreement is resolved by re-reading
-- GET /v1/commands/:id, never by "fixing" a row here.
--
-- DEPENDENCY: the `command.created` reconciliation path updates
-- `ops_dispatcher_actions.control_service_command_id`, added by the
-- immediately-preceding migration 20260808110000. This file deliberately does
-- NOT create that column — two migrations independently adding the same column
-- is exactly the failure documented in 20260808100000__ops_users_vehicle_id_index.sql.
-- The runtime code degrades gracefully (logs a warning and skips reconciliation
-- on SQLSTATE 42703 undefined_column) so an out-of-order environment misbehaves
-- loudly rather than 500-ing a signed delivery.
--
-- AUDIT TRAIL NOTE — why nothing here writes ops_audit_log:
--   `ops_audit_log.actor_user_id` is `not null references ops_users (id)` and
--   the table carries an append-only trigger (ops_audit_log_prevent_mutation).
--   A control-service-originated event has no ops user behind it. Recording
--   machine events there would require either a synthetic ops_users row (a fake
--   human in the one table whose entire purpose is human attribution) or
--   relaxing the NOT NULL (weakening the immutability guarantee). Neither is
--   acceptable, so `ops_control_service_webhook_events` IS the machine-event
--   record: it stores the full signed payload verbatim and joins to the
--   command. The complete end-to-end trail is a three-way join —
--     ops_audit_log            (the human who approved: dispatcher.approval.create)
--       -> ops_dispatcher_actions.control_service_command_id
--       -> ops_command_mirror.command_id
--       -> ops_control_service_webhook_events.command_id (every machine event since)
--
-- Idempotent: every statement is safe to re-run. Do not edit this file once
-- applied anywhere; add a new migration for any follow-up change.

begin;

-- ============================================================================
-- ops_control_service_webhook_events — one row per accepted signed delivery
-- ============================================================================
--
-- Written BEFORE any side effect runs ("store then process"), so a delivery
-- that is accepted is never lost even if processing subsequently fails. The
-- primary key is the sender's idempotency key, which makes the insert itself
-- the deduplication mechanism: `on conflict do nothing returning ...` returns
-- zero rows for a repeat delivery, and the handler then branches on
-- `processed_at` (see the route handler's three-way branch — inserted /
-- duplicate-already-processed / duplicate-still-unprocessed-so-reprocess).

create table if not exists ops_control_service_webhook_events (
  -- Sender-chosen key, taken from the SIGNED body rather than the (unsigned)
  -- x-control-service-idempotency-key header. Format is per-event-type and
  -- deterministic: `<commandId>`, `<commandId>:delivered:v<version>`,
  -- `<commandId>:ack:<acknowledgedAt>`, `<commandId>:superseded`.
  idempotency_key text primary key,
  event_type      text not null,
  -- data.command.id when the payload carries one, else null (an unknown/future
  -- event type is still recorded — see the handler's forward-compatibility
  -- 200 response). Not a foreign key: control-service owns command identity.
  command_id      uuid,
  -- The verified envelope exactly as received. Retained in full so an event
  -- whose side effects need re-running later (a bug fix, a new projection) can
  -- be replayed from this table without asking control-service to re-deliver —
  -- control-service has no persistent outbox, so anything it fails to deliver
  -- three times is gone forever and this is the only copy that survives.
  payload         jsonb not null,
  received_at     timestamptz not null default now(),
  -- Null until every side effect for this event has succeeded. A null here on
  -- an existing row is what licenses re-processing a duplicate delivery: every
  -- side effect is an idempotent upsert, so re-running is always safe, and
  -- without this branch one transient failure would swallow the event forever.
  processed_at    timestamptz,
  process_error   text,
  attempts        integer not null default 0
);

comment on table ops_control_service_webhook_events is
  'One row per verified inbound control-service webhook delivery (POST /api/control-service/webhook). Written before side effects run and marked processed after they succeed, so nothing accepted is ever lost. This is the machine-event audit record; ops_audit_log is for human-attributed actions only (its actor_user_id is NOT NULL references ops_users) and this handler never writes it.';

comment on column ops_control_service_webhook_events.payload is
  'The full verified envelope {type, idempotencyKey, data}. This is the only durable copy: control-service dispatches with no outbox (control-service/src/webhooks/dispatch.ts), so an event it fails to deliver is unrecoverable from the sender side.';

comment on column ops_control_service_webhook_events.processed_at is
  'Null = side effects have not all succeeded yet. A duplicate delivery of a row with processed_at null is deliberately re-processed rather than short-circuited.';

-- Command timeline lookups ("show me every machine event for this command"),
-- newest first — the read pattern behind an incident/command drill-down.
create index if not exists ops_cs_webhook_events_command_idx
  on ops_control_service_webhook_events (command_id, received_at desc);

-- Partial index over the (expected to be tiny) backlog of events whose side
-- effects have not completed. Kept proportional to the stuck set rather than
-- to the whole event log, same reasoning as ops_users_vehicle_id_idx.
create index if not exists ops_cs_webhook_events_unprocessed_idx
  on ops_control_service_webhook_events (received_at)
  where processed_at is null;

-- ============================================================================
-- ops_command_status_rank — lifecycle ordering, used only as a tiebreaker
-- ============================================================================
--
-- Last-write-wins on the mirror is decided by EVENT time, never arrival time
-- (see ops_command_mirror below). Event time comes from the payload/verified
-- header and is only second-resolution in the fallback case, so two events for
-- one command can legitimately tie. This rank breaks such a tie in lifecycle
-- order so a `delivered` retry landing in the same second as an `acknowledged`
-- can never regress the mirror. Terminal states rank highest: once a command
-- is expired/cancelled/failed, nothing earlier should overwrite it.

create or replace function ops_command_status_rank(status text)
returns integer
language sql
immutable
as $$
  select case status
    when 'proposed'          then 0
    when 'awaiting_approval' then 1
    when 'authorized'        then 2
    when 'delivered'         then 3
    when 'acknowledged'      then 4
    when 'executing'         then 5
    when 'completed'         then 6
    when 'expired'           then 7
    when 'cancelled'         then 8
    when 'failed'            then 9
    else -1
  end;
$$;

comment on function ops_command_status_rank(text) is
  'Lifecycle ordering for control-service command statuses. Tiebreaker only, for two mirror writes carrying an identical event timestamp; ordering across different event timestamps is always by event time. Unknown statuses rank -1 so a future status never silently outranks a known one.';

-- ============================================================================
-- ops_command_mirror — this app's projection of control-service command state
-- ============================================================================
--
-- Without this table the webhook would be decorative: `command.delivered` and
-- `command.acknowledged` would have nowhere to land, and the control room
-- would still have to poll to discover that a driver answered UNABLE or
-- UNSAFE. One row per command, upserted by the webhook handler.
--
-- ORDERING (the subtle part): control-service retries with backoff and does
-- not serialize deliveries, so a retried `command.delivered` can arrive AFTER
-- `command.acknowledged`. Every write is therefore guarded by
--   on conflict (command_id) do update ... where <newer by event time>
-- so arrival order is irrelevant and the mirror never visibly regresses from
-- acknowledged back to delivered.

create table if not exists ops_command_mirror (
  -- control-service commands.id. Not a foreign key (different database).
  command_id             uuid primary key,
  -- ops_dispatcher_actions.id — the human approval this command was issued
  -- against. Not declared as a foreign key: the command can legitimately
  -- arrive before/without a local dispatcher action row in a partially
  -- reconciled environment, and a webhook must never fail on that.
  dispatcher_action_id   uuid,
  vehicle_id             text,
  -- Not carried on control-service's CommandRow today; backfilled from the
  -- referenced ops_dispatcher_actions row when one exists, so route-scoped
  -- reads do not need a join. Never overwritten with null by a later event.
  route_direction_id     text,
  action_type            text,
  status                 text,
  version                integer,
  supersedes_command_id  uuid,
  ttl_seconds            integer,
  expires_at             timestamptz,
  delivered_at           timestamptz,
  acknowledged_at        timestamptz,
  -- accept | unable | unsafe (blueprint 9.2). The operationally important
  -- column: 'unable'/'unsafe' is how the control room learns a driver
  -- declined a command without polling for it.
  ack_outcome            text,
  acknowledgement_reason text,
  -- Event time of the newest event applied to this row (NOT arrival time).
  -- The write guard compares against this, so replays and out-of-order
  -- retries are no-ops instead of regressions.
  last_event_at          timestamptz not null,
  updated_at             timestamptz not null default now()
);

comment on table ops_command_mirror is
  'Read-only projection of control-service command lifecycle state, maintained by POST /api/control-service/webhook. Control-service remains the source of truth (docs/CONTROL_SERVICE_INTEGRATION.md §1/§3); rows here are eventually consistent and are reconciled by re-reading GET /v1/commands/:id, never by editing this table by hand.';

comment on column ops_command_mirror.last_event_at is
  'Event time (command.updatedAt / the event''s own natural timestamp / the verified x-control-service-timestamp), never arrival time. Every upsert is guarded on this being >= the stored value so an out-of-order retry cannot regress the row.';

comment on column ops_command_mirror.ack_outcome is
  'Driver acknowledgement outcome: accept | unable | unsafe. Populated from command.acknowledged events — the push path that replaces control-room polling for driver refusals.';

-- Control-room reads: "commands for this vehicle, newest activity first".
create index if not exists ops_command_mirror_vehicle_idx
  on ops_command_mirror (vehicle_id, last_event_at desc);

-- Backs the reconciliation sweep for commands that are past their TTL but
-- never reached a terminal state — the compensating control for
-- control-service having no persistent webhook outbox.
create index if not exists ops_command_mirror_open_idx
  on ops_command_mirror (expires_at)
  where status not in ('completed', 'expired', 'cancelled', 'failed');

-- Joins back from a dispatcher approval to the command it produced.
create index if not exists ops_command_mirror_dispatcher_action_idx
  on ops_command_mirror (dispatcher_action_id)
  where dispatcher_action_id is not null;

drop trigger if exists set_updated_at on ops_command_mirror;
create trigger set_updated_at before update on ops_command_mirror
  for each row execute function ops_set_updated_at();

commit;
