-- Driver breakdown-report submission — audited, persisted follow-up to the
-- parent RBAC migration (20260805210000__ops_rbac.sql).
--
-- BreakdownReportPanel.tsx (src/components/ops/driver/) previously only
-- composed a read-out-loud text summary because no audited-action endpoint
-- existed for the driver role (see that parent ticket's own out-of-scope
-- note: only the dispatcher/approvals and control-room/commands endpoints
-- were in scope there). This migration adds the table POST
-- /api/ops/driver/breakdown-reports writes to, following the same
-- ops_dispatcher_actions pattern: one row per submission, attributable to
-- the reporting driver's ops_users row, plus one ops_audit_log row per
-- submission (written by the route handler via repo.recordAuditEvent, not
-- by this migration).
--
-- Idempotent: every statement is safe to re-run. Do not edit this file once
-- applied anywhere; add a new migration for any follow-up change.

begin;

create table if not exists ops_breakdown_reports (
  id               uuid primary key default gen_random_uuid(),
  driver_user_id   uuid not null references ops_users (id) on delete restrict,
  vehicle_reg      text not null,
  category         text not null check (category in (
                     'Mechanical', 'Electrical', 'Tyre/wheel', 'Accident', 'Other'
                   )),
  description      text not null,
  created_at       timestamptz not null default now()
);

comment on table ops_breakdown_reports is
  'One row per driver-submitted breakdown report, created by POST /api/ops/driver/breakdown-reports. Keyed to ops_users.id (this app''s RBAC identity), same attribution pattern as ops_dispatcher_actions. Append-mostly operational record — no update path exists yet; a correction is a new report, not an edit, mirroring the audit log''s append-only stance one layer down.';

create index if not exists ops_breakdown_reports_driver_idx
  on ops_breakdown_reports (driver_user_id, created_at desc);

commit;
