-- Link ops_users forward to Supabase Auth identities (Phase 1 of collapsing
-- the app's two auth systems into one front door).
--
-- PROVENANCE: this app has carried TWO independent auth systems since the ops
-- RBAC ticket — Supabase Auth for /project/* and /api/upsrtc/* (no roles, one
-- flat "project viewer"), and a self-contained ops session for /ops/* and
-- /api/ops/* (its own cookie, its own HS256 secret, its own bcrypt password
-- column). Phase 1 makes Supabase the single front door while KEEPING
-- ops_users as the role/profile table. This migration is the whole schema
-- half of that: one nullable column and two indexes. Nothing is dropped,
-- renamed or rewritten.
--
-- WHY LINK FORWARD RATHER THAN RE-KEY. The obvious alternative — replacing
-- ops_users.id with the Supabase user's uuid — is not merely harder, it is
-- blocked by design. ops_users.id is the FK target of 14 columns across 8
-- tables (ops_audit_log.actor_user_id, ops_invites.invited_by,
-- ops_dispatcher_actions.dispatcher_user_id/.rejected_by/.claimed_by,
-- ops_copilot_interactions.actor_user_id, ops_shift_report_drafts.*,
-- ops_breakdown_reports.driver_user_id, ops_kill_switches.*,
-- ops_users.created_by/.disabled_by), five of them `not null` +
-- `on delete restrict`. Two of those tables — ops_audit_log
-- (20260805210000) and ops_copilot_interactions (20260806140000) — carry
-- BEFORE UPDATE/DELETE triggers that raise on every row, deliberately, so the
-- trail is append-only and tamper-evident. Re-keying would require dropping
-- those triggers, mutating the audit trail, and recreating them: dismantling
-- the exact control they exist to provide, and leaving no evidence it
-- happened. It would also have to stay consistent with control-service's
-- `dispatcher_actions.dispatcher_id`, a plain text column in a SEPARATE
-- database this app holds no write credentials for
-- (docs/CONTROL_SERVICE_INTEGRATION.md sections 1 and 3) — so the rewrite
-- could not be made consistent even in principle.
--
-- Adding a nullable column alongside the primary key leaves all 14 FKs
-- pointing at an unchanged ops_users.id, rewrites no rows, exercises no
-- `on delete restrict`, and never touches either append-only trigger.
--
-- WHY NULLABLE, AND WHY IT STAYS NULLABLE FOR NOW. Nullable is what makes the
-- cutover reversible: both auth paths work at once, unlinked rows keep
-- signing in with their existing password_hash, and rollback is a config
-- change rather than a data restore. A `not null` constraint here would be a
-- lockout waiting for the first unlinked account. Tightening it (if ever) is
-- a later migration, after the new path has been the only path for a stated
-- soak period.
--
-- WHY THE UNIQUE INDEX ON supabase_user_id IS PARTIAL. A plain UNIQUE would
-- already permit many NULLs in Postgres, so the partial form is not about
-- permissiveness — it states the intent (many unlinked legacy rows; at most
-- ONE ops_users row per Supabase identity) and keeps the index proportional
-- to the linked cohort. That uniqueness is load-bearing: the Node-runtime
-- guard resolves a signed-in Supabase user to exactly one ops profile via
-- this column (findUserBySupabaseId in src/lib/auth/rbac/repo.ts), and two
-- rows claiming one identity would make that resolution nondeterministic.
--
-- WHY THE UNIQUE INDEX ON lower(email) IS ADDED HERE TOO. ops_users.email is
-- already UNIQUE, but case-SENSITIVELY (ops_users_email_key, plain btree),
-- while findUserByEmail queries `where lower(email) = lower($1) limit 1` with
-- no ORDER BY and Supabase treats the address case-insensitively as one login
-- identity. Two rows differing only in case would therefore make login
-- nondeterministic today AND collapse onto a single Supabase identity
-- tomorrow, violating the partial unique index above. ops_invites already
-- carries exactly this index; ops_users was the inconsistency. It is free to
-- add now (no such rows exist) and impossible to add once one appears, so it
-- belongs in the same migration as the linkage that depends on it. If this
-- statement fails on some environment, that environment HAS a collision and
-- must resolve it before any account can be linked — aborting here is the
-- correct outcome, not an obstacle.
--
-- NOT touched by this migration, on purpose: password_hash (still `not null`,
-- still populated — it is the entire rollback mechanism and the only
-- credential path that still works if Supabase Auth is unreachable), the
-- ops_invites flow, and every FK and trigger listed above.
--
-- Idempotent: safe to re-run. Do not edit this file once applied anywhere;
-- add a new migration for any follow-up change.

begin;

alter table ops_users add column if not exists supabase_user_id uuid;

comment on column ops_users.supabase_user_id is
  'The Supabase Auth user (auth.users.id, in the Supabase project named by NEXT_PUBLIC_SUPABASE_URL) that signs in as this ops account. Null means "not linked yet": that account still signs in through the legacy ops password path and its password_hash is authoritative. LINK FORWARD ONLY — this column exists so a Supabase identity can be resolved to an ops profile without re-keying ops_users.id, which is the FK target of 14 columns across 8 tables and of two append-only, trigger-protected audit tables. Never rewrite historical actor ids to Supabase ids. The role that rides in the Supabase JWT (app_metadata.ops_role) is a fast CEILING checked at the edge; ops_users.role and ops_users.status remain the sole authority and are re-read on every guarded request (src/lib/auth/rbac/server.ts).';

-- Partial: unlinked legacy rows stay null and never collide, while at most
-- one ops_users row may ever bind to a given Supabase identity.
create unique index if not exists ops_users_supabase_user_id_uq
  on ops_users (supabase_user_id)
  where supabase_user_id is not null;

-- Makes the case-insensitive lookup the app already performs
-- (findUserByEmail) match a real constraint, and stops two rows differing
-- only in case from collapsing onto one Supabase login identity.
create unique index if not exists ops_users_email_lower_uq
  on ops_users (lower(email));

commit;
