-- Keyset-pagination index on ops_breakdown_reports.
--
-- PROVENANCE: added alongside the fleet-wide read surface GET
-- /api/ops/fleet/breakdown-reports and its "mine" counterpart GET
-- /api/ops/driver/breakdown-reports (src/lib/auth/rbac/repo.ts's
-- listBreakdownReports). The table's existing index,
-- ops_breakdown_reports_driver_idx (driver_user_id, created_at desc) from
-- 20260806120000__ops_breakdown_reports.sql, serves a single driver's own
-- list but cannot serve the fleet-wide scan, which has no driver_user_id
-- predicate to lead on.
--
-- Why this shape: listBreakdownReports orders `by created_at desc, id
-- desc` — id is the tiebreaker for rows sharing the same created_at, which
-- keeps the ordering (and therefore keyset pagination across it) stable
-- and deterministic. A plain (created_at desc) index would satisfy the
-- fleet-wide scan's ORDER BY but leave ties unordered between queries;
-- indexing both columns removes that ambiguity at the index level too.
--
-- Idempotent: safe to re-run. Do not edit this file once applied anywhere;
-- add a new migration for any follow-up change.

begin;

create index if not exists ops_breakdown_reports_created_at_id_idx
  on ops_breakdown_reports (created_at desc, id desc);

commit;
