-- Partial index on ops_users.vehicle_id.
--
-- PROVENANCE: this index is the one genuinely new artifact extracted from
-- db/migrations/20260806200000__ops_users_vehicle_assignment.sql, which has
-- been DELETED. That file was a duplicate of
-- 20260806180000__ops_users_vehicle_assignment.sql: two tickets added
-- `ops_users.vehicle_id` independently, from opposite premises. Because
-- `20260806200000` sorted last, its `comment on column` silently overwrote
-- the security-hardened comment written by `20260806180000` (the OWASP A01
-- fix), so the schema's own documentation ended up describing the permissive
-- posture the A01 fix exists to prevent. It also omitted
-- `ops_invites.vehicle_id`, which the invite-acceptance path
-- (acceptInvite in src/lib/auth/rbac/repo.ts) depends on.
--
-- Resolution: `20260806180000` is the surviving definition of the column and
-- carries the authoritative, per-surface policy comment. This file adds only
-- the index. Nothing had been deployed and neither database held production
-- data when the duplicate was removed, so no environment can have applied
-- `20260806200000` — there is no drop/repair step to perform here.
--
-- Why partial (`where vehicle_id is not null`): the column is nullable and
-- most rows are expected to be null (non-driver roles never get one, and a
-- driver account exists before an admin assigns one). Indexing only the
-- assigned rows keeps the index proportional to the pilot-driver cohort
-- rather than to the whole ops_users table. Supports the assigned-vehicle
-- lookups behind GET /api/ops/pilot-driver/commands and
-- POST /api/ops/admin/users/:id/vehicle's uniqueness/reassignment checks.
--
-- Idempotent: safe to re-run. Do not edit this file once applied anywhere;
-- add a new migration for any follow-up change.

begin;

create index if not exists ops_users_vehicle_id_idx
  on ops_users (vehicle_id)
  where vehicle_id is not null;

commit;
