-- Depot ownership — a real depot registry, a per-user depot assignment, and
-- the authorization boundary that makes /ops/depot show one depot's vehicles
-- instead of the whole state's.
--
-- WHAT THIS CLOSES. Before this migration there was no depot scoping anywhere
-- in this system: no depot column on ops_users, no depot table, no row-level
-- security in either datastore, and /ops/depot called getOpsFleetSnapshot()
-- with no arguments — so every `depot` account saw all ~9,000 vehicles in the
-- statewide UPSRTC feed and could look up any vehicle's schedule through
-- GET /api/ops/fleet/schedule. The only depot notion in the whole system was
-- a nullable display string (control-service vehicles.depot_name, copied from
-- the upstream feed) used for grouping labels, never as a filter and never as
-- an authorization boundary.
--
-- This is a SECURITY BOUNDARY, not a display filter, and it is enforced
-- server-side. See src/lib/ops/depotAccess.ts (resolves the caller's scope
-- from their OWN ops_users row) and src/lib/ops/depotScope.ts (the pure
-- matching rule). The UI never narrows a wider server result.
--
-- Follow-up to the parent RBAC migration (20260805210000__ops_rbac.sql). The
-- fail-closed discipline below is deliberately modelled on the vehicle
-- assignment (20260806180000__ops_users_vehicle_assignment.sql) and its
-- VEHICLE_NOT_ASSIGNED contract — read that file's column comment first; this
-- one is its depot-level twin.
--
-- Idempotent: safe to re-run. Do not edit this file once applied anywhere;
-- add a new migration for any follow-up change.

begin;

-- ============================================================================
-- ops_depots — the depot registry, promoted from the live feed's free text
-- ============================================================================

create table if not exists ops_depots (
  id                uuid primary key default gen_random_uuid(),
  -- Canonical matching key. Derived from `name` by normalizeDepotCode()
  -- in src/lib/ops/depotScope.ts: trim, collapse internal whitespace, upper
  -- case. That one function is used BOTH when a row is seeded here and when a
  -- live vehicle is matched to a depot, so the two can never drift apart.
  code              text not null unique,
  -- Display name, spelled the way the upstream feed spells it.
  name              text not null,
  -- The feed's own numeric `home_depot` id for this depot. PROVENANCE ONLY —
  -- deliberately NOT the matching key; see the note below.
  upstream_depot_id text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

comment on table ops_depots is
  'Depot registry for this app''s own datastore, seeded from the live UPSRTC feed by scripts/seed-ops-depots.mjs. Exists so ops_users.depot_id can be a real foreign key instead of another free-text string: a depot assignment is an authorization boundary, and an authorization boundary keyed on unvalidated free text is one typo away from silently granting nothing (or, worse, the wrong thing). The registry is a snapshot of an upstream vocabulary, not an authority over it — re-running the seed adds newly-seen depots and refreshes names, and never deletes a row an ops_users assignment might point at (the FK is on delete restrict).';

comment on column ops_depots.code is
  'Canonical matching key: normalizeDepotCode(name) — trim, collapse internal whitespace, uppercase. The SAME function derives the code from a live vehicle''s depot_name at query time (src/lib/ops/depotScope.ts), so seeding and matching cannot drift. Unique: two feed spellings that normalize to one code are one depot.';

comment on column ops_depots.upstream_depot_id is
  'The upstream feed''s numeric `home_depot` id for this depot, recorded as provenance and as a debugging aid for reconciling a renamed depot. DELIBERATELY NOT THE MATCHING KEY, and no code path may start matching on it without re-deciding this. Measured against a full live snapshot (9,170 vehicles) the feed''s home_depot ids and depot_name strings are a clean bijection — 143 ids, 143 names, no id carrying two names and no name carrying two ids — so either could serve. Names win on FAILURE MODE, which is what matters for a boundary: if the upstream ever re-uses a numeric id for a different depot, id-matching hands one depot''s buses to another depot''s operator, a silent boundary violation. If a depot is instead renamed, name-matching stops matching and its vehicles become unattributed — visible to nobody until an admin re-seeds. Under-showing is recoverable and obvious; over-showing is a breach.';

drop trigger if exists set_updated_at on ops_depots;
create trigger set_updated_at before update on ops_depots
  for each row execute function ops_set_updated_at();

-- ============================================================================
-- ops_users.depot_id — the per-user assignment that scopes a depot operator
-- ============================================================================

alter table ops_users add column if not exists depot_id uuid;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'ops_users_depot_id_fkey'
  ) then
    alter table ops_users
      add constraint ops_users_depot_id_fkey
      foreign key (depot_id) references ops_depots (id) on delete restrict;
  end if;
end;
$$;

comment on column ops_users.depot_id is
  'The depot this `depot`-role operator owns, set ONLY by an admin (POST /api/ops/admin/users/:id/depot, or at invite time via ops_invites.depot_id). Null means "no depot assigned yet". Unlike vehicle_id this IS a real foreign key (ops_depots) with on delete restrict, because a depot assignment is an authorization boundary and must never point at a depot that does not exist. Meaningless for non-depot roles but left ungated at the schema level, exactly as vehicle_id is for non-driver roles.

HOW TO TREAT NULL — one rule, no per-surface split. This differs from vehicle_id on purpose and this comment is the authoritative statement of it.

EVERY DEPOT-SCOPED SURFACE FAILS CLOSED. Any surface that serves fleet data to a `depot`-role caller MUST derive the depot from the CALLER''s own ops_users row (session subject -> findUserById -> depot_id) and MUST refuse when this column is null: 409 DEPOT_NOT_ASSIGNED on an API route, an explicit "no depot assigned" refusal panel on the page. It must NEVER fall back to the unscoped statewide fleet. A client-supplied depot id, code or name is never accepted, in a query string, a body or a header. Representative files: src/lib/ops/depotAccess.ts (the single resolver), src/app/(ops)/ops/depot/page.tsx, src/app/api/ops/fleet/schedule/route.ts, src/app/api/ops/fleet/breakdown-reports/route.ts.

vehicle_id grants a read-only convenience fallback to a self-reported registration when it is null (see 20260806180000__ops_users_vehicle_assignment.sql). NO SUCH FALLBACK EXISTS HERE, and none may be added. The reasoning that justified it there inverts here: there, the fallback''s worst case was a mis-scoped read of ONE vehicle a driver named themselves; here, the only thing to fall back TO is the entire statewide fleet, which is precisely the exposure this migration exists to remove. An unassigned depot operator seeing nothing is a visible, one-admin-action problem. An unassigned depot operator seeing everything is the bug.

VEHICLES THAT MATCH NO DEPOT are owned by no depot and are therefore shown to NO depot operator — not bucketed into whichever depot happens to be asking, and not shown as a shared "Unassigned depot" pool. A vehicle reaches that state by reporting a null/empty depot_name, the literal string "None" (which the normalizer maps to null), or a name that is not in ops_depots. The existing "Unassigned depot" group in groupByDepot (src/lib/ops/fleetView.ts) is a LABEL for the statewide roster that dispatcher/control-room/planner still see; it is not a depot anyone can be assigned to, and no ops_depots row may ever be created for it. Statewide roles are unaffected by this column entirely.';

create index if not exists ops_users_depot_id_idx on ops_users (depot_id)
  where depot_id is not null;

-- ============================================================================
-- ops_invites.depot_id — assign the depot at invite time, like vehicle_id
-- ============================================================================

alter table ops_invites add column if not exists depot_id uuid;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'ops_invites_depot_id_fkey'
  ) then
    alter table ops_invites
      add constraint ops_invites_depot_id_fkey
      foreign key (depot_id) references ops_depots (id) on delete restrict;
  end if;
end;
$$;

comment on column ops_invites.depot_id is
  'Optional depot assignment to apply to the ops_users row created when this invite is accepted (see acceptInvite in src/lib/auth/rbac/repo.ts), mirroring ops_invites.vehicle_id. Null is valid — the admin can assign a depot later via POST /api/ops/admin/users/:id/depot instead. An invited depot operator who accepts with this null is refused fleet data (fail-closed) until an admin assigns one.';

commit;
