-- Adds the `pilot_driver` role — a follow-up to the parent RBAC migration
-- (20260805210000__ops_rbac.sql) for the "Driver PWA: single-instruction
-- command interface with ack/unable/unsafe" ticket.
--
-- `pilot_driver` is deliberately a role of its own, not a flag on the
-- existing `driver` role: the ticket requires the command interface be
-- "delivered only to the pilot driver pool" — a restricted cohort separate
-- from the general driver population that already has its own dashboard
-- (src/components/ops/driver/DriverDashboard.tsx, schedule lookup +
-- breakdown reporting). A distinct role means:
--   * an admin invite explicitly opts a person into the pilot (no accidental
--     enrolment of every driver by a broader role check),
--   * the command surface at /ops/pilot-driver and /api/ops/pilot-driver/*
--     is reachable only by that role, at both middleware (roleForSegment)
--     and per-route (requireOpsRole(['pilot_driver'])) layers — same
--     defence-in-depth as every other ops role,
--   * a person can later be promoted from `pilot_driver` to `driver` (full
--     rollout) or vice versa purely by admin action, with no code change.
--
-- Idempotent: safe to re-run. Do not edit this file once applied anywhere;
-- add a new migration for any follow-up change.

begin;

alter table ops_users drop constraint if exists ops_users_role_check;
alter table ops_users add constraint ops_users_role_check
  check (role in ('driver', 'pilot_driver', 'dispatcher', 'depot', 'control_room', 'planner', 'admin'));

alter table ops_invites drop constraint if exists ops_invites_role_check;
alter table ops_invites add constraint ops_invites_role_check
  check (role in ('driver', 'pilot_driver', 'dispatcher', 'depot', 'control_room', 'planner', 'admin'));

commit;
