/**
 * Core domain types for Depot Management.
 *
 * This file is the shared contract between the depot modules: it holds only
 * the shapes more than one module needs. Each module keeps its own types
 * beside its code (`infer/types.ts`, `score/types.ts`, `exceptions/types.ts`,
 * `optimise/types.ts`, `sim/types.ts`), and API payloads live in `api.ts`.
 */

/**
 * Where a figure comes from. Every number the module shows carries one:
 *  - `live`      straight from the UPSRTC feed
 *  - `derived`   computed from live data
 *  - `modelled`  generated by the modelled world (rendered MODELLED)
 *  - `reference` curated static data
 */
export type Provenance = 'live' | 'derived' | 'modelled' | 'reference';

/** How much of the population a derived figure actually rests on. */
export interface Coverage {
  readonly n: number;
  readonly of: number;
}

export interface Figure<T = number> {
  readonly value: T;
  readonly provenance: Provenance;
  readonly coverage?: Coverage;
  readonly note?: string;
}

/**
 * The feed's "depots" include units that are not operating depots
 * (enforcement squads, hired and electric fleets). They are listed but never
 * ranked against real depots.
 */
export type DepotKind = 'depot' | 'hired' | 'electric' | 'enforcement' | 'unassigned';

/** Bucket id for buses whose feed record carries no home depot. */
export const UNASSIGNED_DEPOT_ID = 'unassigned';

/** Counts by upstream `vehicle_status`, exactly as the feed reports it. */
export interface StatusMix {
  readonly live: number;
  readonly stationary: number;
  readonly noSignal: number;
  readonly underMaintenance: number;
  readonly unknown: number;
}

/**
 * Operational state inferred for one bus from the live snapshot:
 *  - `in_service` moving with a route assignment
 *  - `on_road`    moving with no schedule in the feed
 *  - `standing`   heard from recently, not moving
 *  - `dark`       no signal, or no fix for hours
 *  - `off_road`   flagged under maintenance upstream
 */
export type BusOpState = 'in_service' | 'on_road' | 'standing' | 'dark' | 'off_road';

/** Counts by inferred operational state. Always sums to the depot's fleet. */
export interface StateMix {
  readonly inService: number;
  readonly onRoad: number;
  readonly standing: number;
  readonly dark: number;
  readonly offRoad: number;
}

export interface LatLng {
  readonly lat: number;
  readonly lng: number;
}

export interface DepotSummary {
  readonly id: string;
  readonly name: string;
  readonly kind: DepotKind;
  /** Every registration homed here, with or without a GPS fix. */
  readonly fleet: number;
  readonly status: StatusMix;
  readonly states: StateMix;
  /** Buses with a GPS fix inside the reporting window around feedNow. */
  readonly reporting: number;
  /** Buses with a valid position. */
  readonly positioned: number;
  /** Buses carrying a route name. */
  readonly assigned: number;
  /** Buses whose main power reads off. */
  readonly powerCut: number;
  /** Buses whose tamper code is present and not the normal `C`. */
  readonly tamperFlagged: number;
  /** Median position of the depot's positioned buses; null when none. */
  readonly centroid: LatLng | null;
}

export interface NetworkKpis {
  readonly fleet: Figure;
  readonly depots: Figure;
  readonly reporting: Figure;
  /** Classified state: in service or moving. With the next three it partitions the fleet. */
  readonly onRoad: Figure;
  /** Classified state: standing. */
  readonly stationary: Figure;
  /** Classified state: dark (no signal for the dark threshold or longer). */
  readonly noSignal: Figure;
  /** Classified state: off road. */
  readonly underMaintenance: Figure;
  readonly assigned: Figure;
}

/** How many feed records populate one field; shown on the Data Sources page. */
export interface FieldCoverage {
  readonly field: string;
  readonly label: string;
  readonly populated: number;
  readonly of: number;
}
