-- route_policies.calibration_source: make a FABRICATED target headway
-- distinguishable from a derived one.
--
-- Extends control-service/db/migrations/20260805190000__core_data_model.sql
-- (route_policies, and specifically its target_headway_seconds column).
-- Idempotent: every statement is safe to re-run. Do not edit this file once
-- applied anywhere; add a new migration for any follow-up change.
--
-- Columns added: route_policies.calibration_source.

begin;

-- ============================================================================
-- calibration_source -- provenance for target_headway_seconds (H*)
-- ============================================================================

-- WHY THIS COLUMN EXISTS.
--
-- target_headway_seconds is H*, the denominator of the entire detection
-- system. src/headway/bunching.ts flags an incident on hFwd/H* against
-- bunched_threshold_ratio (0.25) and warning_threshold_ratio (0.5), and
-- src/headway/metrics.ts reports CV and EWT relative to it. So H* is not one
-- number among many in this table: it sets the scale everything else is
-- measured against.
--
-- The failure mode a wrong H* produces is SILENCE, not an error. The network
-- seeder must write something -- target_headway_seconds is `not null check
-- (> 0)` -- so when it cannot derive a target it writes a configured fallback.
-- A fallback of 1,800s against a route whose real mean headway is ~19,000s
-- yields a ratio around 10, which never crosses 0.5 and therefore never crosses
-- 0.25 either: that route is quietly excluded from bunching detection for as
-- long as the row stands. Nothing logs, nothing 500s, no incident is ever
-- raised. On the same rows the observability dashboard's CV and EWT are ratios
-- against an invented target and mean nothing (MEASURED on a live route seeded
-- this way: CV 1.63, EWT 34,493s).
--
-- Before this column existed there was no way to tell those rows apart from
-- genuinely derived ones except by guessing from the value -- and 429 of 653
-- seeded route-directions (66%) carried the fallback. Downstream consumers
-- (the dashboard, the KPI snapshotter, anyone reading a CV) must be able to ask
-- "is this route's target real?" and get an answer, so the seeder now records
-- which method produced each H* and this column carries it.
--
-- Values, in the seeder's precedence order (src/seed/harvest.ts
-- #deriveTargetHeadway):
--
--   'journey_span'  >=2 deduped journey start times published by the schedule
--                   feed for this route-direction; H* = span / (n - 1).
--                   Strongest available evidence: real departures over the
--                   same road.
--   'fleet_span'    The same estimator over the scheduled_start_time values the
--                   LIVE feed publishes for every vehicle assigned to this
--                   direction's routenames. Headway is a property of how many
--                   vehicles serve a route, and the seeder probes exactly one
--                   representative vehicle per routename, so this reaches the
--                   large set of directions 'journey_span' structurally cannot.
--                   Weaker than 'journey_span': some live assignments are a
--                   vehicle's last known duty from an earlier day, so treat it
--                   as a fleet-level estimate, not a timetable reading.
--   'default'       NOT DERIVED. The configured fallback
--                   (--default-headway-seconds, 1,800s unless overridden).
--                   Detection on this route-direction is effectively off. Any
--                   consumer that would present a threshold, a CV or an EWT for
--                   such a row should suppress it or mark it uncalibrated
--                   rather than render a number computed against a number
--                   nobody measured.
--
-- The column is `not null default 'default'`, which back-fills every row that
-- predates this migration as 'default'. That is deliberately the pessimistic
-- reading: those rows' provenance genuinely was not recorded, so claiming a
-- derivation for them would be inventing exactly the confidence this column
-- exists to remove. The next seeder run re-versions them with their true source
-- (src/seed/persist.ts#upsertPolicy compares calibration_source, so a policy
-- whose only change is its provenance is still closed and re-inserted).
--
-- Values are constrained rather than free text because they are read as an
-- enumeration by both the seeder and anything grouping by them, and a typo'd
-- source would misreport a fabricated target as a derived one -- the single
-- outcome this column is here to prevent.
alter table route_policies
  add column if not exists calibration_source text not null default 'default'
    check (calibration_source in ('journey_span', 'fleet_span', 'default'));

comment on column route_policies.calibration_source is
  'How target_headway_seconds (H*) was obtained, written by the network seeder (src/seed/harvest.ts). ''journey_span'' = span/(n-1) over >=2 scheduled journey starts for this route-direction; ''fleet_span'' = the same estimator over the scheduled_start_time values the live feed publishes for the fleet assigned to this direction''s routenames; ''default'' = NOT DERIVED, a configured fallback was written because target_headway_seconds is not-null. A fabricated H* disables detection silently rather than producing a visible error -- every threshold in src/headway/ is a ratio of H*, so a fallback far from the real headway simply never crosses 0.25 or 0.5 and the route-direction is never flagged, while its CV and EWT are ratios against an invented target. Consumers MUST treat ''default'' as uncalibrated and not present its thresholds, CV or EWT as measurements. Rows predating this column were back-filled ''default'' because their provenance was unrecorded; the next seeder run re-versions them with their true source.';

commit;
