-- Pilot-staging dashboard: per-route rollout gates, daily KPI snapshots,
-- guardrail-breach audit and war-room incident review.
--
-- Extends control-service/db/migrations/20260805190000__core_data_model.sql
-- (route_directions, bunching_incidents, commands, dispatcher_actions,
-- headway_states) and 20260806120000__command_lifecycle.sql (command_audit_log
-- immutability pattern, reused here for the two append-only tables below).
-- Idempotent: every statement is safe to re-run. Do not edit this file once
-- applied anywhere; add a new migration for any follow-up change.
--
-- Tables created: route_direction_rollout_stages, rollout_stage_audit_log,
-- guardrail_breach_log, war_room_incident_reviews, daily_kpi_snapshots.

begin;

-- ============================================================================
-- route_direction_rollout_stages — one live stage per route-direction
-- ============================================================================

-- The pilot cadence (blueprint-style staged rollout): observation (detect
-- only, never command) -> shadow (compute recommendations, still never
-- command) -> advisory (human-approved commands only — already this
-- service's default posture, since every command requires a
-- dispatcher_action_id) -> limited_auto (a constrained action set may run
-- with reduced friction) -> expanded (full authorized action set). A
-- missing row for a route-direction defaults to 'observation' in
-- application code (src/pilot/rolloutStages.ts) — the safest posture, so a
-- route-direction newly onboarded to this table never accidentally starts
-- more permissive than intended.
create table if not exists route_direction_rollout_stages (
  route_direction_id  uuid primary key references route_directions (id) on delete cascade,
  stage               text not null default 'observation'
                       check (stage in ('observation', 'shadow', 'advisory', 'limited_auto', 'expanded')),
  reason              text,
  updated_by          text not null,
  updated_at          timestamptz not null default now(),
  created_at          timestamptz not null default now()
);

comment on table route_direction_rollout_stages is
  'Current pilot rollout stage per route-direction. Read directly by POST /v1/commands (src/pilot/gate.ts) before every command insert — flipping a row here changes command-service behaviour immediately, with no deploy (ticket AC1).';

drop trigger if exists set_updated_at on route_direction_rollout_stages;
create trigger set_updated_at before update on route_direction_rollout_stages
  for each row execute function control_service_set_updated_at();

-- ============================================================================
-- rollout_stage_audit_log — append-only history of every stage change
-- ============================================================================

create table if not exists rollout_stage_audit_log (
  id                  uuid primary key default gen_random_uuid(),
  route_direction_id  uuid not null references route_directions (id) on delete cascade,
  previous_stage      text,
  new_stage           text not null,
  changed_by          text not null,
  reason              text,
  created_at          timestamptz not null default now()
);

comment on table rollout_stage_audit_log is
  'Append-only record of every route_direction_rollout_stages change (ticket AC4: "stage changes ... audit-logged and visible without waiting for day-end"). Written in the same transaction as the stage update by src/pilot/rolloutStages.ts#setRolloutStage.';

create index if not exists rollout_stage_audit_log_route_direction_idx
  on rollout_stage_audit_log (route_direction_id, created_at desc);

create or replace function control_service_rollout_stage_audit_log_immutable()
returns trigger
language plpgsql
as $$
begin
  raise exception 'rollout_stage_audit_log is append-only; % is not permitted', tg_op;
end;
$$;

drop trigger if exists rollout_stage_audit_log_no_update on rollout_stage_audit_log;
create trigger rollout_stage_audit_log_no_update before update on rollout_stage_audit_log
  for each row execute function control_service_rollout_stage_audit_log_immutable();

drop trigger if exists rollout_stage_audit_log_no_delete on rollout_stage_audit_log;
create trigger rollout_stage_audit_log_no_delete before delete on rollout_stage_audit_log
  for each row execute function control_service_rollout_stage_audit_log_immutable();

-- ============================================================================
-- guardrail_breach_log — append-only, real-time (ticket AC4)
-- ============================================================================

-- Scope of this ticket's slice: a "guardrail breach" is an attempt to issue
-- a command on a route-direction whose rollout stage forbids commands
-- entirely (observation/shadow) — the gate in src/pilot/gate.ts logs one
-- row here for every rejection, in the same request that rejects it, so
-- it is queryable immediately (GET /v1/guardrail-breaches), never batched
-- to a day-end job. detail carries the rejected action/vehicle/dispatcher-
-- action so the war room can see exactly what was attempted.
create table if not exists guardrail_breach_log (
  id                  uuid primary key default gen_random_uuid(),
  route_direction_id  uuid references route_directions (id) on delete cascade,
  breach_type         text not null,
  severity            text not null default 'warning' check (severity in ('info', 'warning', 'critical')),
  detail              jsonb not null default '{}'::jsonb,
  detected_at         timestamptz not null default now()
);

comment on table guardrail_breach_log is
  'Append-only, real-time guardrail-breach record (ticket AC4). Populated by src/pilot/gate.ts whenever a command is rejected for violating its route-direction''s rollout stage.';

create index if not exists guardrail_breach_log_route_direction_idx
  on guardrail_breach_log (route_direction_id, detected_at desc);

create or replace function control_service_guardrail_breach_log_immutable()
returns trigger
language plpgsql
as $$
begin
  raise exception 'guardrail_breach_log is append-only; % is not permitted', tg_op;
end;
$$;

drop trigger if exists guardrail_breach_log_no_update on guardrail_breach_log;
create trigger guardrail_breach_log_no_update before update on guardrail_breach_log
  for each row execute function control_service_guardrail_breach_log_immutable();

drop trigger if exists guardrail_breach_log_no_delete on guardrail_breach_log;
create trigger guardrail_breach_log_no_delete before delete on guardrail_breach_log
  for each row execute function control_service_guardrail_breach_log_immutable();

-- ============================================================================
-- war_room_incident_reviews — one editable review row per bunching incident
-- ============================================================================

-- Distinct from bunching_incidents.cause_class (endogenous/exogenous/
-- structural/unknown — the detection system's own attribution, blueprint
-- 7.4): this is the war-room's own classification vocabulary for the pilot
-- cadence review (ticket AC3: "eligible/exogenous/structural"), plus the
-- action taken and outcome the reviewer records. Editable (unlike the two
-- audit-log tables above) because a war-room review is revised as an
-- incident's story develops, not an immutable event log.
create table if not exists war_room_incident_reviews (
  id              uuid primary key default gen_random_uuid(),
  incident_id     uuid not null unique references bunching_incidents (id) on delete cascade,
  classification  text not null check (classification in ('eligible', 'exogenous', 'structural')),
  action_taken    text,
  outcome         text,
  reviewed_by     text not null,
  reviewed_at     timestamptz not null default now(),
  created_at      timestamptz not null default now()
);

comment on table war_room_incident_reviews is
  'One reviewable row per bunching_incidents.id, written by PUT /v1/war-room/incidents/:incidentId/review (ticket AC3). Upserted on unique(incident_id) as the war-room revises its classification/action/outcome.';

drop trigger if exists set_updated_at on war_room_incident_reviews;
create trigger set_updated_at before update on war_room_incident_reviews
  for each row execute function control_service_set_updated_at();

-- ============================================================================
-- daily_kpi_snapshots — one row per route-direction per day
-- ============================================================================

-- Computed on demand (src/pilot/dailyKpi.ts#computeDailyKpiSnapshot, reusing
-- the same CV/EWT formula as the live observability dashboard —
-- src/headway/metrics.ts#computeAggregate) from that day's headway_states /
-- bunching_incidents / guardrail_breach_log / outcomes rows, then upserted
-- here so a day's numbers stop moving once the day is over and so the
-- dashboard has real per-day history to trend against (ticket AC2 "daily
-- EWT, CV, recovery rate, guardrail breaches, and compliance per route").
-- Today's row is recomputed on every read — see the same doc-comment
-- pattern as src/lib/controlService/observabilityData.ts on the web side.
create table if not exists daily_kpi_snapshots (
  id                     uuid primary key default gen_random_uuid(),
  route_direction_id     uuid not null references route_directions (id) on delete cascade,
  snapshot_date          date not null,
  sample_count           integer not null default 0,
  mean_headway_seconds   numeric,
  ewt_seconds            numeric,
  cv                     numeric,
  incident_count         integer not null default 0,
  recovered_incident_count integer not null default 0,
  recovery_rate          numeric,
  guardrail_breach_count integer not null default 0,
  compliance_sample_count integer not null default 0,
  compliance_pct         numeric,
  computed_at            timestamptz not null default now(),
  unique (route_direction_id, snapshot_date)
);

comment on table daily_kpi_snapshots is
  'One upserted row per route-direction per calendar day (ticket AC2). recovery_rate = recovered_incident_count / incident_count (incidents that reached status=closed that day); compliance_pct = outcomes.compliance=''complied'' share of outcomes rows linked to that day''s incidents.';

create index if not exists daily_kpi_snapshots_route_direction_date_idx
  on daily_kpi_snapshots (route_direction_id, snapshot_date desc);

commit;
