/**
 * An interactive, browser-real harness for the control-room console.
 *
 * ─── WHY THIS EXISTS ─────────────────────────────────────────────────────
 *
 * The console cannot be opened the ordinary way in a review environment: every
 * ops page is behind `requireOpsRolePage`, which needs a real Supabase session
 * for one of the seeded operator accounts, and the end-to-end suite's default
 * origin is the port the captain's live app already occupies. Reviewing the
 * screen by taking that port, or by weakening the guard, would both be wrong.
 *
 * So this mounts the REAL ControlRoomConsole - the same component the guarded
 * page renders, with the real design system and the real Tailwind build - in a
 * real browser, and stubs only the network. Every interaction under review
 * (tab switching, the engine panel's staging and confirmation, the approval
 * queue's approve and reject, the kill-switch form, prefill into the command
 * form) is the shipped code path, and the requests it makes are captured so
 * they can be asserted rather than eyeballed.
 *
 * ─── WHAT IS REAL AND WHAT IS NOT ────────────────────────────────────────
 *
 * Sibling `preview-control-room-data.json` is generated by
 * `scripts/capture-control-room-fixture.ts` from the captain's own running
 * control service: real corridor ids, real UPSRTC registration numbers, a real
 * solve, real daily KPI rows. The scenarios below say which is which, on the
 * page, in a banner - a harness that looked like production would be the same
 * dishonesty this whole phase exists to remove.
 *
 * Run it with scripts/serve-control-room-preview.mjs, which bundles this entry
 * with esbuild and serves it on a scratch port.
 */
import { createRoot } from 'react-dom/client';
import { StrictMode, useState } from 'react';
import { ControlRoomConsole } from '../src/components/ops/control-room/console/ControlRoomConsole';
import type { ControlRoomOverview } from '../src/lib/ops/controlRoomOverviewModel';
import type { RecommendationResult } from '../src/lib/ops/recommendationView';

interface Fixture {
  capturedAt: string;
  corridors: { routeDirectionId: string; routeId: string; directionCode: string; isLoop: boolean; totalDistanceMeters: number }[];
  liveSolve: Record<string, unknown>;
  kpiRow: Record<string, unknown> | null;
  vehicles: { id: string; registrationNumber: string; latitude: number; longitude: number; headingDegrees: number | null; dataQuality: string; depotName: string | null; routeName: string | null; speedKmph: number | null; stopState: string | null; routeDirectionId: string | null; positionSource: string; observedAt: string }[];
  headway: Record<string, unknown> | null;
}

declare global {
  interface Window {
    __FIXTURE__: Fixture;
    __REQUESTS__: { url: string; method: string; body: unknown }[];
  }
}

const fixture = window.__FIXTURE__;
window.__REQUESTS__ = [];

const CORRIDOR = fixture.corridors[0]!.routeDirectionId;

/** The live truth, as captured: every candidate refused for a stale reading. */
const liveRejected: RecommendationResult = {
  routeDirectionId: CORRIDOR,
  solvedAt: new Date().toISOString(),
  controllerVersion: String(fixture.liveSolve.controllerVersion ?? 'terminal-two-way-self-equalizing-v1'),
  engineActionTypes: ['terminal_dispatch_hold', 'two_way_hold', 'self_equalizing_hold'],
  selectedAction: null,
  selectionBasis: 'all_candidates_rejected',
  objectiveCost: null,
  expectedRecoverySeconds: null,
  candidateActions: (fixture.liveSolve.candidateActions ?? []) as RecommendationResult['candidateActions'],
  safeCandidates: [],
  rejectedCandidates: (fixture.liveSolve.rejectedCandidates ?? []) as RecommendationResult['rejectedCandidates'],
  predictiveAdvisory: fixture.liveSolve.predictiveAdvisory as RecommendationResult['predictiveAdvisory'],
  constraints: (fixture.liveSolve.constraints ?? {}) as Record<string, unknown>,
  commandsBlockedBy: null,
  persistence: 'none',
};

/**
 * A proposal the operator can act on.
 *
 * Constructed, and labelled as such on the page. It has to be: on the captain's
 * live system right now the safety filter refuses every candidate on every
 * corridor, so there is no real solve anywhere that exercises the issue path.
 * The candidate's own numbers are lifted from a real rejected one so the shapes
 * and magnitudes are true to the system.
 */
const firstRealCandidate = (liveRejected.rejectedCandidates[0]?.candidate ?? null);
const proposed: RecommendationResult = {
  ...liveRejected,
  selectionBasis: 'lowest_cost_mid_route',
  selectedAction: firstRealCandidate
    ? { ...firstRealCandidate, stateAsOf: new Date().toISOString(), objectiveCost: 0, holdSeconds: 42 }
    : null,
  safeCandidates: firstRealCandidate
    ? [{ ...firstRealCandidate, stateAsOf: new Date().toISOString(), objectiveCost: 0, holdSeconds: 42 }]
    : [],
  rejectedCandidates: liveRejected.rejectedCandidates.slice(1, 4),
  objectiveCost: 0,
  expectedRecoverySeconds: 42,
};

const APPROVAL = {
  id: '9f1c2f2a-7f1e-4a5b-9c3d-2b6e5a4d8c11',
  dispatcherUserId: 'dispatcher-1',
  actionType: proposed.selectedAction?.actionType ?? 'two_way_hold',
  vehicleId: proposed.selectedAction?.vehicleId ?? 'UP78HN2039',
  routeDirectionId: CORRIDOR,
  incidentId: null,
  reason: 'Bunching reported by Agra depot supervisor; approving a hold.',
  consumedAt: null,
  rejectedAt: null,
  rejectedBy: null,
  rejectionReason: null,
  createdAt: new Date(Date.now() - 4 * 60_000).toISOString(),
  decision: 'pending' as const,
};

const DISRUPTIVE_APPROVAL = {
  ...APPROVAL,
  id: '4c2f8e11-3a7d-4c9e-8b21-77d0a1f5e903',
  actionType: 'stop_skip',
  vehicleId: 'UP78KN2230',
  reason: 'Skip Sikandra stop — crowd control request from the district administration.',
  createdAt: new Date(Date.now() - 11 * 60_000).toISOString(),
};

function overviewFor(scenario: Scenario): ControlRoomOverview {
  const degraded = scenario === 'degraded';
  return {
    fetchedAt: new Date().toISOString(),
    corridorsPlaceholder: undefined,
    routeDirections: fixture.corridors,
    selectedRouteDirectionId: CORRIDOR,
    fleet: degraded
      ? { reporting: 0, source: 'unavailable', stale: true, error: 'upstream feed did not respond' }
      : { reporting: 9170, source: 'live', stale: false, error: null },
    observability: degraded
      ? { ok: false, stale: true, error: 'control service timed out' }
      : { ok: true, stale: false, error: null },
    headway: degraded ? null : (fixture.headway as ControlRoomOverview['headway']),
    incidents: [],
    dailyKpi: degraded
      ? { ok: false, row: null }
      : { ok: true, row: fixture.kpiRow as ControlRoomOverview['dailyKpi']['row'] },
    guardrails: degraded ? { ok: false, total: 0, critical: 0 } : { ok: true, total: 0, critical: 0 },
    killSwitches:
      scenario === 'killswitch'
        ? {
            ok: true,
            active: [
              {
                id: 'ks-live-1',
                scope: 'network' as const,
                routeDirectionId: null,
                engagedAt: new Date(Date.now() - 90_000).toISOString(),
                engagedBy: 'control@upsrtc.example',
                reason: 'Statewide comms degradation — holding all automated commands.',
                disengagedAt: null,
                disengagedBy: null,
                disengageReason: null,
              },
            ],
          }
        : { ok: true, active: [] },
  } as unknown as ControlRoomOverview;
}

type Scenario = 'proposal' | 'live-rejected' | 'degraded' | 'killswitch';

let scenario: Scenario = (new URLSearchParams(location.search).get('scenario') as Scenario) || 'proposal';

const realFetch = window.fetch.bind(window);
window.fetch = (async (input: RequestInfo | URL, init?: RequestInit) => {
  const url = typeof input === 'string' ? input : input.toString();
  const method = init?.method ?? 'GET';
  let body: unknown = null;
  try {
    body = init?.body ? JSON.parse(String(init.body)) : null;
  } catch {
    body = String(init?.body ?? '');
  }
  if (url.startsWith('/api/')) window.__REQUESTS__.push({ url, method, body });

  const json = (payload: unknown, status = 200) =>
    new Response(JSON.stringify(payload), { status, headers: { 'content-type': 'application/json' } });

  if (url.startsWith('/api/ops/control-room/overview')) return json(overviewFor(scenario));
  if (url.startsWith('/api/ops/control-room/recommendations')) {
    if (scenario === 'degraded') {
      return json(
        { error: { code: 'CONTROL_SERVICE_ERROR', message: 'Unexpected response shape from /v1/mpc/solve' } },
        502,
      );
    }
    const result = scenario === 'proposal' ? proposed : liveRejected;
    const withKill =
      scenario === 'killswitch'
        ? {
            ...proposed,
            commandsBlockedBy: {
              scope: 'network' as const,
              routeDirectionId: null,
              reason: 'Statewide comms degradation — holding all automated commands.',
              engagedAt: new Date(Date.now() - 90_000).toISOString(),
            },
          }
        : result;
    return json({ ...withKill, solvedAt: new Date().toISOString() });
  }
  if (url.startsWith('/api/ops/dispatcher/approvals')) {
    return json({ actions: scenario === 'live-rejected' ? [DISRUPTIVE_APPROVAL] : [APPROVAL, DISRUPTIVE_APPROVAL] });
  }
  if (url.startsWith('/api/ops/control-room/commands/') && method === 'GET') {
    return json({
      command: {
        id: 'cmd-1',
        status: 'acknowledged',
        deliveredAt: new Date(Date.now() - 30_000).toISOString(),
        acknowledgedAt: new Date(Date.now() - 20_000).toISOString(),
        ackOutcome: 'accept',
        acknowledgementReason: null,
      },
      auditLog: [
        { id: 'a1', eventType: 'created', actorType: 'control_room', actorId: 'op-1', reason: null, occurredAt: new Date().toISOString() },
        { id: 'a2', eventType: 'delivered', actorType: 'system', actorId: null, reason: null, occurredAt: new Date().toISOString() },
      ],
    });
  }
  if (url.startsWith('/api/ops/control-room/commands') && method === 'POST') {
    return json({ ok: true, commandId: 'cmd-preview-1', status: 'delivered', expiresAt: 'in 120s', auditEventId: 'audit-1' }, 201);
  }
  if (url.includes('/reject')) return json({ ok: true });
  if (url.startsWith('/api/ops/control-room/kill-switches')) {
    if (method === 'POST') return json({ ok: true }, 201);
    return json({ active: overviewFor(scenario).killSwitches.active });
  }
  if (url.startsWith('/api/ops/fleet/map')) {
    return json({
      vehicles: fixture.vehicles,
      incidents: [],
      scopeLabel: 'all depots',
      source: 'live',
      stale: false,
      fetchedAt: new Date().toISOString(),
      error: null,
      controlServiceError: null,
    });
  }
  if (url.startsWith('/api/ops/fleet/breakdown-reports')) {
    return json({
      reports: [
        {
          id: 'br-1',
          vehicleId: 'UP78KN2230',
          reportedAt: new Date(Date.now() - 15 * 60_000).toISOString(),
          category: 'mechanical',
          severity: 'high',
          notes: 'Air brake pressure dropping on the Agra Expressway run.',
          driverEmail: 'driver1@upsrtc.example',
          depotName: 'Agra',
          status: 'open',
        },
      ],
      nextCursor: null,
    });
  }
  if (url.startsWith('/api/ops/control-room/copilot')) {
    return json({ narrative: 'Preview harness: the copilot is not called from this harness.', citations: [] });
  }
  return realFetch(input as RequestInfo, init);
}) as typeof window.fetch;

function Harness() {
  const [, force] = useState(0);
  return (
    <>
      <div
        style={{
          position: 'fixed',
          bottom: 0,
          left: 0,
          right: 0,
          zIndex: 9999,
          background: '#3a1d05',
          color: '#ffd6a5',
          borderTop: '1px solid #7a4a12',
          font: '11px ui-monospace, monospace',
          padding: '6px 12px',
          display: 'flex',
          gap: '10px',
          alignItems: 'center',
        }}
      >
        <strong>REVIEW HARNESS — network stubbed, not a live console.</strong>
        <span>
          corridors / registrations / solve / KPI captured from the live control service at {fixture.capturedAt}.
        </span>
        <span style={{ marginLeft: 'auto' }}>scenario:</span>
        {(['proposal', 'live-rejected', 'killswitch', 'degraded'] as Scenario[]).map((id) => (
          <button
            key={id}
            id={`scenario-${id}`}
            onClick={() => {
              scenario = id;
              force((n) => n + 1);
            }}
            style={{
              background: scenario === id ? '#ffd6a5' : 'transparent',
              color: scenario === id ? '#3a1d05' : '#ffd6a5',
              border: '1px solid #7a4a12',
              borderRadius: 3,
              padding: '2px 8px',
              cursor: 'pointer',
            }}
          >
            {id}
          </button>
        ))}
      </div>
      <ControlRoomConsole
        key={scenario}
        email="control.room@upsrtc.example"
        initialOverview={overviewFor(scenario)}
        initialOverviewError={null}
        initialActiveKillSwitches={overviewFor(scenario).killSwitches.active}
        initialTab="decisions"
        fleetPanel={<div style={{ padding: 16 }}>Fleet roster renders on the server; not part of this harness.</div>}
        reportsPanel={<div style={{ padding: 16 }}>Breakdown reports panel fetches on mount.</div>}
      />
    </>
  );
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <Harness />
  </StrictMode>,
);
