// @vitest-environment node
//
// POST /api/control-service/webhook — the inbound half of the control-service
// integration.
//
// Every signature in this file is generated by mirroring
// control-service/src/webhooks/sign.ts (see src/tests/helpers/
// controlServiceWebhook.ts), never by importing from control-service: the two
// are separately deployed packages, and a hand-mirrored signer means a change
// on either side surfaces as a failing test instead of as a silent skew.
//
// The route handler is exercised directly with the ops datastore replaced by a
// recording fake — same approach as pilotDriverVehicleAssignment.test.ts. The
// fake records the exact SQL and bind parameters, because for this feature the
// SQL *is* the behaviour: the store-then-process three-way branch and the
// mirror's out-of-order write guard are both expressed as ON CONFLICT clauses.
// A companion suite (controlServiceWebhookDb.test.ts) re-proves the same
// guarantees against a real Postgres when one is available.
import { NextRequest } from 'next/server';
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import {
  TEST_SECRET,
  buildCommand,
  buildSignedDelivery,
  serializeEnvelope,
  signWebhookPayload,
  type SignedDelivery,
} from '@/tests/helpers/controlServiceWebhook';

// ---------------------------------------------------------------------------
// Recording fake for the ops datastore
// ---------------------------------------------------------------------------

interface QueryCall {
  text: string;
  params: unknown[];
}

class FakeOpsDbConfigError extends Error {
  constructor(message = 'OPS_DATABASE_URL is not configured') {
    super(message);
    this.name = 'OpsDbConfigError';
  }
}

const queries: QueryCall[] = [];

const dbState = {
  /** Whether `insert ... on conflict do nothing returning` yields a row (i.e. first delivery). */
  insertReturnsRow: true,
  /** `processed_at` of the pre-existing row, consulted only when the insert conflicted. */
  existingProcessedAt: null as string | null,
  /** Injected failure: the first query whose text matches throws. */
  failOn: null as { pattern: RegExp; error: unknown } | null,
};

const fakePool = {
  query: vi.fn(async (text: string, params: unknown[] = []) => {
    queries.push({ text, params });

    if (dbState.failOn && dbState.failOn.pattern.test(text)) {
      throw dbState.failOn.error;
    }
    if (/insert into ops_control_service_webhook_events/.test(text)) {
      return { rows: dbState.insertReturnsRow ? [{ idempotency_key: params[0] }] : [] };
    }
    if (/select processed_at from ops_control_service_webhook_events/.test(text)) {
      return { rows: [{ processed_at: dbState.existingProcessedAt }] };
    }
    return { rows: [] };
  }),
};

vi.mock('@/lib/db/pool', () => ({
  OpsDbConfigError: FakeOpsDbConfigError,
  getOpsPool: () => fakePool,
}));

// ---------------------------------------------------------------------------
// Query-log helpers. Names describe intent so a failure message is readable.
// ---------------------------------------------------------------------------

const eventInserts = () => queries.filter((q) => /insert into ops_control_service_webhook_events/.test(q.text));
const mirrorUpserts = () =>
  queries.filter((q) => /insert into ops_command_mirror/.test(q.text) && !/'cancelled'/.test(q.text));
const mirrorCancels = () =>
  queries.filter((q) => /insert into ops_command_mirror/.test(q.text) && /'cancelled'/.test(q.text));
const reconciles = () => queries.filter((q) => /update ops_dispatcher_actions/.test(q.text));
const processedMarks = () => queries.filter((q) => /set processed_at = now\(\)/.test(q.text));
const failureMarks = () => queries.filter((q) => /set process_error = \$2/.test(q.text));

/**
 * Indexed access that asserts rather than returning `undefined`, so "the query
 * was never issued" fails as a readable test error instead of as a cascade of
 * `possibly undefined` on every following assertion.
 */
function nth(calls: QueryCall[], index: number): QueryCall {
  const call = calls[index];
  if (!call) {
    throw new Error(`expected at least ${index + 1} matching queries, saw ${calls.length}`);
  }
  return call;
}

/** Named accessors for the mirror upsert's positional binds (see upsertMirror). */
const MIRROR_BIND = {
  commandId: 0,
  dispatcherActionId: 1,
  vehicleId: 2,
  routeDirectionId: 3,
  actionType: 4,
  status: 5,
  version: 6,
  supersedesCommandId: 7,
  ttlSeconds: 8,
  expiresAt: 9,
  deliveredAt: 10,
  acknowledgedAt: 11,
  ackOutcome: 12,
  acknowledgementReason: 13,
  lastEventAt: 14,
} as const;

// ---------------------------------------------------------------------------

const WEBHOOK_URL = 'http://localhost:3000/api/control-service/webhook';

function makeRequest(
  delivery: SignedDelivery,
  headerOverrides: Record<string, string | null> = {},
): NextRequest {
  const headers = new Headers(delivery.headers);
  for (const [key, value] of Object.entries(headerOverrides)) {
    if (value === null) headers.delete(key);
    else headers.set(key, value);
  }
  return new NextRequest(WEBHOOK_URL, { method: 'POST', headers, body: delivery.rawBody });
}

async function post(
  delivery: SignedDelivery,
  headerOverrides: Record<string, string | null> = {},
): Promise<Response> {
  const { POST } = await import('@/app/api/control-service/webhook/route');
  return POST(makeRequest(delivery, headerOverrides));
}

let warnSpy: ReturnType<typeof vi.spyOn>;
let errorSpy: ReturnType<typeof vi.spyOn>;

beforeEach(() => {
  vi.clearAllMocks();
  queries.length = 0;
  dbState.insertReturnsRow = true;
  dbState.existingProcessedAt = null;
  dbState.failOn = null;
  process.env.CONTROL_SERVICE_WEBHOOK_SECRET = TEST_SECRET;
  warnSpy = vi.spyOn(console, 'warn').mockImplementation(() => {});
  errorSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
});

afterEach(() => {
  warnSpy.mockRestore();
  errorSpy.mockRestore();
  delete process.env.CONTROL_SERVICE_WEBHOOK_SECRET;
});

// ===========================================================================
describe('control-service webhook — signature verification', () => {
  it('accepts a correctly signed delivery and applies the side effect', async () => {
    const command = buildCommand({ status: 'delivered' });
    const delivery = buildSignedDelivery({
      type: 'command.delivered',
      idempotencyKey: `${command.id}:delivered:v1`,
      data: { command },
    });

    const response = await post(delivery);
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body).toMatchObject({ ok: true, type: 'command.delivered' });
    expect(mirrorUpserts()).toHaveLength(1);
    expect(nth(mirrorUpserts(), 0).params[MIRROR_BIND.commandId]).toBe(command.id);
  });

  it('rejects a tampered body with 400 and never reaches the JSON parser or the datastore', async () => {
    const command = buildCommand();
    const signed = buildSignedDelivery({
      type: 'command.delivered',
      idempotencyKey: `${command.id}:delivered:v1`,
      data: { command },
    });
    // One byte of the vehicle id flipped after signing — the classic
    // man-in-the-middle edit.
    const tampered: SignedDelivery = {
      ...signed,
      rawBody: signed.rawBody.replace('BUS-100', 'BUS-999'),
    };

    const response = await post(tampered);
    const body = await response.json();

    expect(response.status).toBe(400);
    expect(body.error.code).toBe('INVALID_SIGNATURE');
    // The whole point of verifying before parsing: an unauthenticated caller
    // reaches neither JSON.parse nor Postgres.
    expect(queries).toHaveLength(0);
  });

  it('rejects a re-serialized body whose bytes differ from the signed original (400)', async () => {
    // THE regression this test exists for: if the handler ever did
    // `request.json()` and re-stringified before hashing, this delivery would
    // verify — the two byte strings parse to the same value. It must not.
    const command = buildCommand();
    const data = { command };
    const idempotencyKey = `${command.id}:delivered:v1`;
    const canonical = serializeEnvelope('command.delivered', idempotencyKey, data);

    // Semantically identical, byte-wise different: envelope keys reordered.
    const reordered = JSON.stringify({ data, idempotencyKey, type: 'command.delivered' });
    expect(reordered).not.toBe(canonical);
    expect(JSON.parse(reordered)).toEqual(JSON.parse(canonical));

    const response = await post(
      buildSignedDelivery({
        type: 'command.delivered',
        idempotencyKey,
        data,
        signedBodyOverride: canonical,
        rawBodyOverride: reordered,
      }),
    );

    expect(response.status).toBe(400);
    expect((await response.json()).error.code).toBe('INVALID_SIGNATURE');
    expect(queries).toHaveLength(0);
  });

  it('accepts a non-canonical body that was signed as sent, proving the raw bytes are hashed', async () => {
    // The mirror image of the test above. `1.20e2` parses to 120 and would
    // re-serialize as `120`, so a handler that hashed a re-serialization would
    // compute a DIFFERENT digest and reject this valid delivery — the failure
    // that looks exactly like a misconfigured secret.
    const command = buildCommand();
    const idempotencyKey = `${command.id}:delivered:v1`;
    const canonical = serializeEnvelope('command.delivered', idempotencyKey, { command });
    const nonCanonical = canonical.replace('"ttlSeconds":120', '"ttlSeconds":1.20e2');

    expect(nonCanonical).not.toBe(canonical);
    expect(JSON.stringify(JSON.parse(nonCanonical))).toBe(canonical);

    const response = await post(
      buildSignedDelivery({
        type: 'command.delivered',
        idempotencyKey,
        data: { command },
        signedBodyOverride: nonCanonical,
      }),
    );

    expect(response.status).toBe(200);
    expect(nth(mirrorUpserts(), 0).params[MIRROR_BIND.ttlSeconds]).toBe(120);
  });

  it('rejects a signature computed with a different secret', async () => {
    const command = buildCommand();
    const response = await post(
      buildSignedDelivery({
        type: 'command.delivered',
        idempotencyKey: `${command.id}:delivered:v1`,
        data: { command },
        secret: 'not-the-shared-secret',
      }),
    );

    expect(response.status).toBe(400);
    expect((await response.json()).error.code).toBe('INVALID_SIGNATURE');
  });

  it('rejects a `sha256=`-prefixed signature — the contract is bare lowercase hex', async () => {
    const command = buildCommand();
    const delivery = buildSignedDelivery({
      type: 'command.delivered',
      idempotencyKey: `${command.id}:delivered:v1`,
      data: { command },
    });
    const prefixed = `sha256=${delivery.headers['x-control-service-signature']}`;

    const response = await post(delivery, { 'x-control-service-signature': prefixed });
    expect(response.status).toBe(400);
  });

  it('returns 400 rather than throwing on a signature of the wrong length or non-hex', async () => {
    // timingSafeEqual throws on mismatched buffer lengths; that must not
    // become a 5xx, which the sender WOULD retry (3 attempts, ~15s) on an
    // attacker-controlled request.
    const command = buildCommand();
    const delivery = buildSignedDelivery({
      type: 'command.delivered',
      idempotencyKey: `${command.id}:delivered:v1`,
      data: { command },
    });

    for (const bogus of ['', 'abcd', 'z'.repeat(64), '0'.repeat(128)]) {
      const response = await post(delivery, { 'x-control-service-signature': bogus });
      expect(response.status).toBe(400);
    }
    expect(queries).toHaveLength(0);
  });

  it('rejects a delivery missing any of the three control-service headers', async () => {
    const command = buildCommand();
    const delivery = buildSignedDelivery({
      type: 'command.delivered',
      idempotencyKey: `${command.id}:delivered:v1`,
      data: { command },
    });

    for (const header of [
      'x-control-service-signature',
      'x-control-service-timestamp',
      'x-control-service-idempotency-key',
    ]) {
      const response = await post(delivery, { [header]: null });
      expect(response.status).toBe(400);
      expect((await response.json()).error.code).toBe('MISSING_SIGNATURE_HEADERS');
    }
  });

  it('authenticates on the HMAC alone — no Authorization header is sent or required', async () => {
    const command = buildCommand();
    const delivery = buildSignedDelivery({
      type: 'command.delivered',
      idempotencyKey: `${command.id}:delivered:v1`,
      data: { command },
    });

    expect(Object.keys(delivery.headers).map((h) => h.toLowerCase())).not.toContain('authorization');
    expect((await post(delivery)).status).toBe(200);
  });
});

// ===========================================================================
describe('control-service webhook — timestamp window', () => {
  const command = buildCommand();
  const args = {
    type: 'command.delivered' as const,
    idempotencyKey: `${command.id}:delivered:v1`,
    data: { command },
  };

  it('rejects a timestamp older than the 300s skew window', async () => {
    const stale = Math.floor(Date.now() / 1000) - 301;
    const response = await post(buildSignedDelivery({ ...args, timestampSeconds: stale }));

    expect(response.status).toBe(400);
    expect((await response.json()).error.code).toBe('STALE_TIMESTAMP');
    expect(queries).toHaveLength(0);
  });

  it('rejects a future timestamp beyond the skew window', async () => {
    const future = Math.floor(Date.now() / 1000) + 301;
    const response = await post(buildSignedDelivery({ ...args, timestampSeconds: future }));

    expect(response.status).toBe(400);
    expect((await response.json()).error.code).toBe('STALE_TIMESTAMP');
  });

  it('accepts a timestamp inside the window in both directions', async () => {
    const now = Math.floor(Date.now() / 1000);
    for (const ts of [now - 299, now, now + 299]) {
      queries.length = 0;
      const response = await post(buildSignedDelivery({ ...args, timestampSeconds: ts }));
      expect(response.status).toBe(200);
    }
  });

  it('rejects a millisecond or ISO timestamp — the contract is Unix SECONDS', async () => {
    const delivery = buildSignedDelivery(args);
    const rawTimestamp = delivery.headers['x-control-service-timestamp'];

    for (const bad of [`${rawTimestamp}000`, new Date().toISOString(), '-1', '1.5', 'abc']) {
      // Re-sign over the malformed timestamp so the request fails on the
      // timestamp check specifically, not incidentally on the signature.
      const resigned: SignedDelivery = {
        rawBody: delivery.rawBody,
        headers: {
          ...delivery.headers,
          'x-control-service-timestamp': bad,
          'x-control-service-signature': signWebhookPayload(delivery.rawBody, bad, TEST_SECRET),
        },
      };
      const response = await post(resigned);
      expect(response.status).toBe(400);
      expect((await response.json()).error.code).toBe('INVALID_TIMESTAMP');
    }
  });
});

// ===========================================================================
describe('control-service webhook — status codes tuned to the sender retry policy', () => {
  // The sender retries only 408/429/>=500 (control-service/src/webhooks/
  // dispatch.ts:isRetryableStatus), so every code below is a decision about
  // whether the event gets another chance or is dropped forever.

  it('answers 503 (retryable) when CONTROL_SERVICE_WEBHOOK_SECRET is unset', async () => {
    delete process.env.CONTROL_SERVICE_WEBHOOK_SECRET;
    const command = buildCommand();
    const response = await post(
      buildSignedDelivery({
        type: 'command.delivered',
        idempotencyKey: `${command.id}:delivered:v1`,
        data: { command },
      }),
    );

    expect(response.status).toBe(503);
    expect((await response.json()).error.code).toBe('NOT_CONFIGURED');
    expect(queries).toHaveLength(0);
  });

  it('answers 503 when the secret is present but blank', async () => {
    process.env.CONTROL_SERVICE_WEBHOOK_SECRET = '   ';
    const command = buildCommand();
    const response = await post(
      buildSignedDelivery({
        type: 'command.delivered',
        idempotencyKey: `${command.id}:delivered:v1`,
        data: { command },
      }),
    );
    expect(response.status).toBe(503);
  });

  it('answers 413 for an oversized body, before spending any CPU on the HMAC', async () => {
    const command = buildCommand({ parameters: { note: 'x'.repeat(300_000) } });
    const response = await post(
      buildSignedDelivery({
        type: 'command.delivered',
        idempotencyKey: `${command.id}:delivered:v1`,
        data: { command },
      }),
    );

    expect(response.status).toBe(413);
    expect((await response.json()).error.code).toBe('PAYLOAD_TOO_LARGE');
    expect(queries).toHaveLength(0);
  });

  it('measures the size cap in BYTES, so a multi-byte body cannot slip past it', async () => {
    // 120_000 three-byte characters is 360 KB on the wire but only 120_000
    // UTF-16 code units, so a `String.length` cap of 256_000 would wave it
    // through — the exact payload someone probing this endpoint would send.
    const command = buildCommand({ parameters: { note: 'あ'.repeat(120_000) } });
    const delivery = buildSignedDelivery({
      type: 'command.delivered',
      idempotencyKey: `${command.id}:delivered:v1`,
      data: { command },
    });

    expect(delivery.rawBody.length).toBeLessThan(256_000);
    expect(Buffer.byteLength(delivery.rawBody, 'utf8')).toBeGreaterThan(256_000);

    const response = await post(delivery);
    expect(response.status).toBe(413);
    expect(queries).toHaveLength(0);
  });

  it('answers 400 (not retryable) for unparseable JSON that is nonetheless correctly signed', async () => {
    const garbage = '{"type":"command.delivered", oops';
    const timestamp = String(Math.floor(Date.now() / 1000));
    const response = await post({
      rawBody: garbage,
      headers: {
        'content-type': 'application/json',
        'x-control-service-timestamp': timestamp,
        'x-control-service-signature': signWebhookPayload(garbage, timestamp, TEST_SECRET),
        'x-control-service-idempotency-key': 'whatever',
      },
    });

    expect(response.status).toBe(400);
    expect((await response.json()).error.code).toBe('INVALID_BODY');
    expect(queries).toHaveLength(0);
  });

  it('answers 400 for a structurally invalid envelope', async () => {
    const response = await post(
      buildSignedDelivery({
        type: 'command.delivered',
        idempotencyKey: 'k-1',
        // `data` must be an object; an array is not an envelope.
        data: [] as unknown as Record<string, unknown>,
      }),
    );
    expect(response.status).toBe(400);
    expect((await response.json()).error.code).toBe('INVALID_BODY');
  });

  it('answers 400 for a known event type whose payload violates the contract, after persisting it', async () => {
    const command = buildCommand({ status: 'not_a_real_status' });
    const response = await post(
      buildSignedDelivery({
        type: 'command.acknowledged',
        idempotencyKey: `${command.id}:ack:2026-08-08T06:01:00.000Z`,
        data: { command },
      }),
    );

    expect(response.status).toBe(400);
    expect((await response.json()).error.code).toBe('INVALID_EVENT');
    // Stored for diagnosis, marked failed, never processed, no side effects.
    expect(eventInserts()).toHaveLength(1);
    expect(failureMarks()).toHaveLength(1);
    expect(processedMarks()).toHaveLength(0);
    expect(mirrorUpserts()).toHaveLength(0);
  });

  it('answers 503 (retryable) when the ops datastore is not configured', async () => {
    dbState.failOn = { pattern: /insert into ops_control_service_webhook_events/, error: new FakeOpsDbConfigError() };
    const command = buildCommand();
    const response = await post(
      buildSignedDelivery({
        type: 'command.delivered',
        idempotencyKey: `${command.id}:delivered:v1`,
        data: { command },
      }),
    );

    expect(response.status).toBe(503);
    expect((await response.json()).error.code).toBe('NOT_CONFIGURED');
  });

  it('answers 503 (retryable) when the datastore is down, so nothing is dropped', async () => {
    dbState.failOn = {
      pattern: /insert into ops_control_service_webhook_events/,
      error: Object.assign(new Error('connection refused'), { code: 'ECONNREFUSED' }),
    };
    const command = buildCommand();
    const response = await post(
      buildSignedDelivery({
        type: 'command.delivered',
        idempotencyKey: `${command.id}:delivered:v1`,
        data: { command },
      }),
    );

    expect(response.status).toBe(503);
    expect((await response.json()).error.code).toBe('STORAGE_UNAVAILABLE');
  });

  it('answers 500 and leaves processed_at null when a side effect fails', async () => {
    dbState.failOn = { pattern: /insert into ops_command_mirror/, error: new Error('deadlock detected') };
    const command = buildCommand();
    const response = await post(
      buildSignedDelivery({
        type: 'command.delivered',
        idempotencyKey: `${command.id}:delivered:v1`,
        data: { command },
      }),
    );

    expect(response.status).toBe(500);
    expect((await response.json()).error.code).toBe('PROCESSING_FAILED');
    expect(failureMarks()).toHaveLength(1);
    expect(nth(failureMarks(), 0).params[1]).toContain('deadlock detected');
    expect(processedMarks()).toHaveLength(0);
  });
});

// ===========================================================================
describe('control-service webhook — store-then-process idempotency', () => {
  const command = buildCommand();
  const args = {
    type: 'command.delivered' as const,
    idempotencyKey: `${command.id}:delivered:v1`,
    data: { command },
  };

  it('records the delivery BEFORE running side effects and marks it processed after', async () => {
    await post(buildSignedDelivery(args));

    const order = queries.map((q) => q.text);
    const insertAt = order.findIndex((t) => /insert into ops_control_service_webhook_events/.test(t));
    const mirrorAt = order.findIndex((t) => /insert into ops_command_mirror/.test(t));
    const processedAt = order.findIndex((t) => /set processed_at = now\(\)/.test(t));

    expect(insertAt).toBeGreaterThanOrEqual(0);
    expect(insertAt).toBeLessThan(mirrorAt);
    expect(mirrorAt).toBeLessThan(processedAt);
  });

  it('keys deduplication on the SIGNED body key, not the unsigned header', async () => {
    // The header is not covered by the HMAC, so it can be rewritten in flight;
    // the body's key cannot. A mismatch is logged, not rejected.
    const delivery = buildSignedDelivery(args);
    const response = await post(delivery, { 'x-control-service-idempotency-key': 'attacker-chosen' });

    expect(response.status).toBe(200);
    expect(nth(eventInserts(), 0).params[0]).toBe(args.idempotencyKey);
    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringContaining('idempotency key header disagrees'),
      expect.anything(),
    );
  });

  it('short-circuits a duplicate that was already processed — 200 with NO repeated side effect', async () => {
    dbState.insertReturnsRow = false; // the insert conflicted
    dbState.existingProcessedAt = '2026-08-08T06:00:20.000Z';

    const response = await post(buildSignedDelivery(args));
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body).toMatchObject({ ok: true, duplicate: true });
    expect(mirrorUpserts()).toHaveLength(0);
    expect(reconciles()).toHaveLength(0);
    expect(processedMarks()).toHaveLength(0);
  });

  it('RE-PROCESSES a duplicate whose processed_at is still null', async () => {
    // Without this branch one transient side-effect failure would swallow the
    // event permanently: control-service has no outbox to replay it from.
    dbState.insertReturnsRow = false;
    dbState.existingProcessedAt = null;

    const response = await post(buildSignedDelivery(args));
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body.duplicate).toBeUndefined();
    expect(mirrorUpserts()).toHaveLength(1);
    expect(processedMarks()).toHaveLength(1);
  });

  it('recovers across deliveries: a failed side effect succeeds on the sender retry', async () => {
    dbState.failOn = { pattern: /insert into ops_command_mirror/, error: new Error('transient') };
    expect((await post(buildSignedDelivery(args))).status).toBe(500);
    expect(mirrorUpserts()).toHaveLength(1); // attempted, threw

    // The sender retries the 500. The row now exists with processed_at null.
    queries.length = 0;
    dbState.failOn = null;
    dbState.insertReturnsRow = false;
    dbState.existingProcessedAt = null;

    expect((await post(buildSignedDelivery(args))).status).toBe(200);
    expect(mirrorUpserts()).toHaveLength(1);
    expect(processedMarks()).toHaveLength(1);
  });
});

// ===========================================================================
describe('control-service webhook — the four event types', () => {
  it('command.created seeds the mirror and links the dispatcher action', async () => {
    const command = buildCommand({ status: 'authorized', deliveredAt: null });
    const response = await post(
      buildSignedDelivery({
        type: 'command.created',
        idempotencyKey: String(command.id), // the sender uses the bare command id
        data: { command },
      }),
    );

    expect(response.status).toBe(200);
    expect(mirrorUpserts()).toHaveLength(1);
    expect(nth(mirrorUpserts(), 0).params[MIRROR_BIND.status]).toBe('authorized');
    expect(reconciles()).toHaveLength(1);
    expect(nth(reconciles(), 0).params).toEqual([command.id, command.dispatcherActionId]);
    // It only fills a gap; it never re-points an existing link or steals a
    // command id another dispatcher action already claimed.
    expect(nth(reconciles(), 0).text).toMatch(/control_service_command_id is null/);
    expect(nth(reconciles(), 0).text).toMatch(/not exists/);
  });

  it('command.created still succeeds where ops_dispatcher_actions.control_service_command_id is absent', async () => {
    // That column arrives in migration 20260808110000, which is owned by a
    // different change set. Until it lands, Postgres raises 42703
    // undefined_column — and losing the mirror write over a missing
    // reconciliation column would be a far worse trade.
    dbState.failOn = {
      pattern: /update ops_dispatcher_actions/,
      error: Object.assign(new Error('column "control_service_command_id" does not exist'), { code: '42703' }),
    };
    const command = buildCommand();
    const response = await post(
      buildSignedDelivery({ type: 'command.created', idempotencyKey: String(command.id), data: { command } }),
    );

    expect(response.status).toBe(200);
    expect(mirrorUpserts()).toHaveLength(1);
    expect(processedMarks()).toHaveLength(1);
    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringContaining('control_service_command_id is missing'),
      expect.anything(),
    );
  });

  it('command.created surfaces a non-42703 reconciliation failure as a retryable 500', async () => {
    dbState.failOn = {
      pattern: /update ops_dispatcher_actions/,
      error: Object.assign(new Error('deadlock detected'), { code: '40P01' }),
    };
    const command = buildCommand();
    const response = await post(
      buildSignedDelivery({ type: 'command.created', idempotencyKey: String(command.id), data: { command } }),
    );

    expect(response.status).toBe(500);
    expect(processedMarks()).toHaveLength(0);
  });

  it('command.delivered mirrors delivered_at and the version', async () => {
    const command = buildCommand({
      status: 'delivered',
      version: 2,
      deliveredAt: '2026-08-08T06:00:10.000Z',
    });
    const response = await post(
      buildSignedDelivery({
        type: 'command.delivered',
        idempotencyKey: `${command.id}:delivered:v2`,
        data: { command },
      }),
    );

    expect(response.status).toBe(200);
    const binds = nth(mirrorUpserts(), 0).params;
    expect(binds[MIRROR_BIND.status]).toBe('delivered');
    expect(binds[MIRROR_BIND.version]).toBe(2);
    expect(binds[MIRROR_BIND.deliveredAt]).toBe('2026-08-08T06:00:10.000Z');
    expect(binds[MIRROR_BIND.lastEventAt]).toBe('2026-08-08T06:00:10.000Z');
  });

  it('command.acknowledged mirrors the ack outcome and reason — the push that replaces polling', async () => {
    const command = buildCommand({
      status: 'acknowledged',
      deliveredAt: '2026-08-08T06:00:10.000Z',
      acknowledgedAt: '2026-08-08T06:00:45.000Z',
      ackOutcome: 'unsafe',
      acknowledgementReason: 'road blocked by a procession',
    });
    const response = await post(
      buildSignedDelivery({
        type: 'command.acknowledged',
        idempotencyKey: `${command.id}:ack:${command.acknowledgedAt}`,
        data: { command },
      }),
    );

    expect(response.status).toBe(200);
    const binds = nth(mirrorUpserts(), 0).params;
    expect(binds[MIRROR_BIND.status]).toBe('acknowledged');
    expect(binds[MIRROR_BIND.ackOutcome]).toBe('unsafe');
    expect(binds[MIRROR_BIND.acknowledgementReason]).toBe('road blocked by a procession');
    expect(binds[MIRROR_BIND.lastEventAt]).toBe('2026-08-08T06:00:45.000Z');
  });

  it('command.superseded mirrors the new command and cancels the one it replaced', async () => {
    const supersededId = '33333333-3333-4333-8333-333333333333';
    const command = buildCommand({
      id: '44444444-4444-4444-8444-444444444444',
      status: 'authorized',
      supersedesCommandId: supersededId,
      deliveredAt: null,
      createdAt: '2026-08-08T06:05:00.000Z',
    });
    const response = await post(
      buildSignedDelivery({
        type: 'command.superseded',
        idempotencyKey: `${command.id}:superseded`,
        data: { command, supersedesCommandId: supersededId },
      }),
    );

    expect(response.status).toBe(200);
    expect(mirrorUpserts()).toHaveLength(1);
    expect(nth(mirrorUpserts(), 0).params[MIRROR_BIND.commandId]).toBe(command.id);
    expect(nth(mirrorUpserts(), 0).params[MIRROR_BIND.supersedesCommandId]).toBe(supersededId);

    expect(mirrorCancels()).toHaveLength(1);
    expect(nth(mirrorCancels(), 0).params).toEqual([supersededId, '2026-08-08T06:05:00.000Z']);
  });

  it('command.superseded without supersedesCommandId is a contract violation (400)', async () => {
    const command = buildCommand();
    const response = await post(
      buildSignedDelivery({
        type: 'command.superseded',
        idempotencyKey: `${command.id}:superseded`,
        data: { command },
      }),
    );

    expect(response.status).toBe(400);
    expect((await response.json()).error.code).toBe('INVALID_EVENT');
    expect(mirrorCancels()).toHaveLength(0);
  });

  it('answers 200 and warns for an unknown event type, storing it without side effects', async () => {
    // Forward compatibility: 4xx-ing a benign new control-service event type
    // would make the sender log delivery errors forever.
    const command = buildCommand();
    const response = await post(
      buildSignedDelivery({
        type: 'command.escalated',
        idempotencyKey: `${command.id}:escalated`,
        data: { command },
      }),
    );
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body).toMatchObject({ ok: true, ignored: true });
    expect(eventInserts()).toHaveLength(1);
    expect(nth(eventInserts(), 0).params[1]).toBe('command.escalated');
    expect(mirrorUpserts()).toHaveLength(0);
    expect(processedMarks()).toHaveLength(1);
    expect(warnSpy).toHaveBeenCalledWith(
      expect.stringContaining('unknown event type'),
      expect.objectContaining({ type: 'command.escalated' }),
    );
  });

  it('never writes ops_audit_log — that table is for human-attributed actions only', async () => {
    // ops_audit_log.actor_user_id is NOT NULL references ops_users(id) behind
    // an append-only trigger. A machine event has no ops user, and inventing a
    // synthetic one would poison the one table whose purpose is attribution.
    for (const [type, key] of [
      ['command.created', 'a'],
      ['command.delivered', 'b'],
      ['command.acknowledged', 'c'],
    ] as const) {
      queries.length = 0;
      const command = buildCommand({
        status: type === 'command.acknowledged' ? 'acknowledged' : 'delivered',
        acknowledgedAt: type === 'command.acknowledged' ? '2026-08-08T06:00:45.000Z' : null,
      });
      await post(buildSignedDelivery({ type, idempotencyKey: key, data: { command } }));
      expect(queries.filter((q) => /ops_audit_log/.test(q.text))).toHaveLength(0);
    }
  });
});

// ===========================================================================
describe('control-service webhook — out-of-order deliveries', () => {
  // control-service retries with backoff (250ms, 500ms) and does not serialize
  // deliveries, so a retried `command.delivered` can land AFTER
  // `command.acknowledged`. Last-write-wins must be by EVENT time, never by
  // arrival time, or a command visibly regresses in the control room.

  const commandId = '55555555-5555-4555-8555-555555555555';
  const deliveredAt = '2026-08-08T06:00:10.000Z';
  const acknowledgedAt = '2026-08-08T06:00:45.000Z';

  const deliveredEvent = buildSignedDelivery({
    type: 'command.delivered',
    idempotencyKey: `${commandId}:delivered:v1`,
    data: { command: buildCommand({ id: commandId, status: 'delivered', deliveredAt }) },
  });
  const acknowledgedEvent = buildSignedDelivery({
    type: 'command.acknowledged',
    idempotencyKey: `${commandId}:ack:${acknowledgedAt}`,
    data: {
      command: buildCommand({
        id: commandId,
        status: 'acknowledged',
        deliveredAt,
        acknowledgedAt,
        ackOutcome: 'accept',
      }),
    },
  });

  it('stamps each mirror write with the EVENT time, so a late `delivered` carries the older stamp', async () => {
    await post(acknowledgedEvent);
    await post(deliveredEvent);

    const ackWrite = nth(mirrorUpserts(), 0);
    const lateDeliveredWrite = nth(mirrorUpserts(), 1);
    expect(ackWrite.params[MIRROR_BIND.status]).toBe('acknowledged');
    expect(ackWrite.params[MIRROR_BIND.lastEventAt]).toBe(acknowledgedAt);
    expect(lateDeliveredWrite.params[MIRROR_BIND.status]).toBe('delivered');
    expect(lateDeliveredWrite.params[MIRROR_BIND.lastEventAt]).toBe(deliveredAt);

    // Arrival order says "delivered last"; event time says otherwise, and
    // event time is what the write is guarded on.
    expect(
      Date.parse(String(lateDeliveredWrite.params[MIRROR_BIND.lastEventAt])),
    ).toBeLessThan(Date.parse(String(ackWrite.params[MIRROR_BIND.lastEventAt])));
  });

  it('guards every mirror write on event time so the older event cannot win', async () => {
    await post(deliveredEvent);
    const sql = nth(mirrorUpserts(), 0).text;

    expect(sql).toMatch(/on conflict \(command_id\) do update set/);
    expect(sql).toMatch(/where excluded\.last_event_at > ops_command_mirror\.last_event_at/);
    // Equal event times (both events falling back to the second-resolution
    // header timestamp) are broken by lifecycle rank, never by arrival.
    expect(sql).toMatch(/ops_command_status_rank\(excluded\.status\)\s*>=\s*ops_command_status_rank/);
  });

  it('derives event time from the payload, falling back to the verified header timestamp', async () => {
    const { eventTimeFor } = await import('@/lib/webhooks/controlServiceEvents');
    const { controlServiceWebhookEventSchema } = await import('@/models/control');
    const headerSeconds = 1_800_000_000; // 2027-01-15T08:00:00.000Z

    const parse = (type: string, command: Record<string, unknown>) =>
      controlServiceWebhookEventSchema.parse({ type, idempotencyKey: 'k', data: { command } });

    expect(
      eventTimeFor(parse('command.acknowledged', buildCommand({ acknowledgedAt })), headerSeconds),
    ).toBe(acknowledgedAt);
    expect(eventTimeFor(parse('command.delivered', buildCommand({ deliveredAt })), headerSeconds)).toBe(
      deliveredAt,
    );
    expect(
      eventTimeFor(parse('command.created', buildCommand({ createdAt: '2026-08-08T06:00:00.000Z' })), headerSeconds),
    ).toBe('2026-08-08T06:00:00.000Z');

    // No usable payload timestamp -> the signed header timestamp.
    const noStamps = buildCommand({ deliveredAt: null, acknowledgedAt: null, createdAt: undefined });
    expect(eventTimeFor(parse('command.delivered', noStamps), headerSeconds)).toBe(
      new Date(headerSeconds * 1000).toISOString(),
    );

    // `updatedAt` outranks everything when control-service starts sending it.
    const withUpdatedAt = buildCommand({ acknowledgedAt, updatedAt: '2026-08-08T07:00:00.000Z' });
    expect(eventTimeFor(parse('command.acknowledged', withUpdatedAt), headerSeconds)).toBe(
      '2026-08-08T07:00:00.000Z',
    );
  });

  it('guards the superseded-command cancellation on event time too', async () => {
    const supersededId = '66666666-6666-4666-8666-666666666666';
    const command = buildCommand({
      id: '77777777-7777-4777-8777-777777777777',
      supersedesCommandId: supersededId,
      createdAt: '2026-08-08T06:05:00.000Z',
    });
    await post(
      buildSignedDelivery({
        type: 'command.superseded',
        idempotencyKey: `${command.id}:superseded`,
        data: { command, supersedesCommandId: supersededId },
      }),
    );

    expect(nth(mirrorCancels(), 0).text).toMatch(
      /where excluded\.last_event_at > ops_command_mirror\.last_event_at/,
    );
  });
});
